; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.export _sounds=sounds

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_jump
	.word @sfx_ntsc_hit
	.word @sfx_ntsc_pickup
	.word @sfx_ntsc_land
	.word @sfx_ntsc_blip
	.word @sfx_ntsc_error

@sfx_ntsc_jump:
	.byte $81,$6a,$82,$00,$80,$3f,$89,$f0,$03,$81,$54,$03,$81,$46,$03,$81
	.byte $34,$03,$00
@sfx_ntsc_hit:
	.byte $81,$7e,$82,$00,$80,$3f,$89,$f0,$03,$81,$9f,$03,$81,$d5,$03,$81
	.byte $fd,$03,$00
@sfx_ntsc_pickup:
	.byte $81,$54,$82,$00,$80,$3f,$89,$f0,$03,$81,$46,$03,$81,$34,$03,$81
	.byte $29,$03,$00
@sfx_ntsc_land:
	.byte $81,$ab,$82,$01,$80,$3f,$89,$f0,$06,$81,$56,$82,$03,$06,$00
@sfx_ntsc_blip:
	.byte $81,$46,$82,$00,$80,$3f,$89,$f0,$03,$81,$3f,$03,$00
@sfx_ntsc_error:
	.byte $81,$d5,$82,$00,$80,$3f,$89,$f0,$03,$81,$e1,$03,$81,$fd,$03,$81
	.byte $1c,$82,$01,$03,$00

.export sounds
