; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for StarterCheerful:

.export _music_data_startercheerful:=music_data_startercheerful

music_data_startercheerful:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : CheerfulLoop
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_startercheerful
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env2,@env3,@env0 ; 00 : bass

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$7f,$00,$02
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $80
@song0ref6:
	.byte $25, $89, $29, $89, $2c, $89, $31, $89, $2c, $89, $29, $89, $2c, $89, $2e, $89
	.byte $41, $08
	.word @song0ref6
	.byte $2e, $89, $2c, $89, $29, $89, $25, $89, $48, $2a, $89, $2e, $89, $31, $89, $2e, $89, $2a, $89, $2e, $89, $31, $89, $33
	.byte $89, $2c, $89, $30, $89, $33, $89, $38, $89, $31, $89, $2c, $89, $29, $89, $25, $89, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $80, $1d, $ad, $20, $ad, $1d, $ad, $22, $ad, $1e, $ad, $22, $ad, $20, $ad, $25, $ad, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $80, $0d, $ad, $0d, $ad, $0d, $ad, $16, $ad, $12, $ad, $12, $ad, $14, $ad, $0d, $ad, $42
	.word @song0ch2loop
@song0ch4:
@song0ch3:
@song0ch3loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song0ch3loop
