; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for StarterTense:

.export _music_data_startertense:=music_data_startertense

music_data_startertense:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : TenseLoop
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_startertense
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env2,@env3,@env0 ; 00 : bass

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$7f,$00,$02
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $80, $22, $89, $25, $89, $29, $89, $2e, $89, $29, $89, $25
	.byte $89, $22, $89, $20, $89, $22, $89, $25, $89, $29, $89, $2c, $89, $2a, $89, $29, $89, $25, $89, $22, $89, $48, $27, $89
	.byte $2a, $89, $2e, $89, $33, $89, $2e, $89, $2a, $89, $27, $89, $25, $89, $29, $89, $2c, $89, $30, $89, $35, $89, $33, $89
	.byte $31, $89, $30, $89, $2e, $89, $42
	.word @song0ch0loop
@song0ch4:
@song0ch3:
@song0ch1:
@song0ch1loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $80, $0a, $dd, $08, $dd, $0f, $dd, $0a, $dd, $42
	.word @song0ch2loop
