;
; File generated by cc65 v 2.18 - Debian 2.19-2
;
; TUNING NOTE:
; Step 3 is still the generated ASM baseline in this tuned directory. The data
; labels below are safe places to change game values while the code routines are
; tuned incrementally:
;   _enemy1_x/_enemy1_y       slime start position
;   _enemy1_left/_enemy1_right slime patrol bounds
;   _enemy2_x/_enemy2_y       skeleton start position
;   _enemy2_left/_enemy2_right skeleton patrol bounds
;   _enemy_speed              frames between enemy moves (lower = faster)
;   _gem_x/_gem_y             gem positions, four bytes each
;   _heart_x/_heart_y         heart pickup position
; Player tunables are initialized in _init_player:
;   x=60, y=176, jump frames=15, floor=176, walk tick limit=7.
	.fopt		compiler,"cc65 v 2.18 - Debian 2.19-2"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_waitvsync
	.import		_load_background
	.export		_main

.segment	"DATA"

_enemy1_x:
	.byte	$96
_enemy1_y:
	.byte	$C0
_enemy1_dir:
	.byte	$01
_enemy1_left:
	.byte	$78
_enemy1_right:
	.byte	$C8
_enemy2_x:
	.byte	$50
_enemy2_y:
	.byte	$80
_enemy2_dir:
	.byte	$01
_enemy2_left:
	.byte	$40
_enemy2_right:
	.byte	$70
_enemy_timer:
	.byte	$00
_enemy_speed:
	.byte	$03
_gem_x:
	.byte	$64
	.byte	$8C
	.byte	$B4
	.byte	$58
_gem_y:
	.byte	$A8
	.byte	$A8
	.byte	$A8
	.byte	$68
_gem_collected:
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
_heart_x:
	.byte	$B0
_heart_y:
	.byte	$68
_heart_collected:
	.byte	$00
_score:
	.byte	$00

.segment	"RODATA"

_anim_tiles:
	.byte	$01
	.byte	$02
	.byte	$11
	.byte	$12
	.byte	$21
	.byte	$22
	.byte	$31
	.byte	$32
	.byte	$09
	.byte	$0A
	.byte	$19
	.byte	$1A
	.byte	$29
	.byte	$2A
	.byte	$39
	.byte	$3A
	.byte	$01
	.byte	$02
	.byte	$11
	.byte	$12
	.byte	$21
	.byte	$22
	.byte	$31
	.byte	$32
	.byte	$0B
	.byte	$0C
	.byte	$1B
	.byte	$1C
	.byte	$2B
	.byte	$2C
	.byte	$3B
	.byte	$3C

.segment	"BSS"

_x:
	.res	1,$00
_y:
	.res	1,$00
_pad:
	.res	1,$00
_jump:
	.res	1,$00
_jmptime:
	.res	1,$00
_plrdir:
	.res	1,$00
_moved:
	.res	1,$00
_moveWait:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ ppu_seek (unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_ppu_seek: near

.segment	"CODE"

	jsr     pusha
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	sta     $2006
	ldy     #$00
	ldx     #$00
	lda     (sp),y
	sta     $2006
	jsr     incsp2
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ reset_scroll (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_reset_scroll: near

.segment	"CODE"

	ldx     #$00
	lda     #$00
	sta     $2005
	ldx     #$00
	lda     #$00
	sta     $2005
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ write_palettes (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_write_palettes: near

.segment	"CODE"

	lda     #$3F
	jsr     pusha
	lda     #$00
	jsr     _ppu_seek
	ldx     #$00
	lda     #$21
	sta     $2007
	ldx     #$00
	lda     #$29
	sta     $2007
	ldx     #$00
	lda     #$19
	sta     $2007
	ldx     #$00
	lda     #$07
	sta     $2007
	lda     #$3F
	jsr     pusha
	lda     #$05
	jsr     _ppu_seek
	ldx     #$00
	lda     #$00
	sta     $2007
	ldx     #$00
	lda     #$10
	sta     $2007
	ldx     #$00
	lda     #$2D
	sta     $2007
	lda     #$3F
	jsr     pusha
	lda     #$11
	jsr     _ppu_seek
	ldx     #$00
	lda     #$30
	sta     $2007
	ldx     #$00
	lda     #$27
	sta     $2007
	ldx     #$00
	lda     #$17
	sta     $2007
	lda     #$3F
	jsr     pusha
	lda     #$15
	jsr     _ppu_seek
	ldx     #$00
	lda     #$1A
	sta     $2007
	ldx     #$00
	lda     #$30
	sta     $2007
	ldx     #$00
	lda     #$0A
	sta     $2007
	lda     #$3F
	jsr     pusha
	lda     #$19
	jsr     _ppu_seek
	ldx     #$00
	lda     #$30
	sta     $2007
	ldx     #$00
	lda     #$16
	sta     $2007
	ldx     #$00
	lda     #$00
	sta     $2007
	lda     #$3F
	jsr     pusha
	lda     #$1D
	jsr     _ppu_seek
	ldx     #$00
	lda     #$16
	sta     $2007
	ldx     #$00
	lda     #$36
	sta     $2007
	ldx     #$00
	lda     #$06
	sta     $2007
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ init_player (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_player: near

.segment	"CODE"

	ldx     #$00
	lda     #$3C
	sta     _x
	ldx     #$00
	lda     #$B0
	sta     _y
	ldx     #$00
	lda     #$00
	sta     _pad
	ldx     #$00
	lda     #$01
	sta     _jump
	ldx     #$00
	lda     #$00
	sta     _jmptime
	ldx     #$00
	lda     #$00
	sta     _plrdir
	ldx     #$00
	lda     #$00
	sta     _moved
	ldx     #$00
	lda     #$00
	sta     _moveWait
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ init_game (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_game: near

.segment	"CODE"

	jsr     _waitvsync
	ldx     #$00
	lda     #$00
	sta     $2001
	jsr     _write_palettes
	jsr     _load_background
	ldx     #$00
	lda     #$10
	sta     $2000
	jsr     _reset_scroll
	ldx     #$00
	lda     #$1E
	sta     $2001
	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ read_controller (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_read_controller: near

.segment	"CODE"

	lda     #$00
	jsr     pusha
	jsr     decsp1
	ldx     #$00
	lda     #$01
	sta     $4016
	ldx     #$00
	lda     #$00
	sta     $4016
	ldx     #$00
	lda     #$00
	ldy     #$00
	sta     (sp),y
L00C4:	ldy     #$00
	ldx     #$00
	lda     (sp),y
	cmp     #$08
	jsr     boolult
	jne     L00C7
	jmp     L00C5
L00C7:	ldy     #$01
	ldx     #$00
	lda     (sp),y
	jsr     shlax1
	ldy     #$01
	sta     (sp),y
	ldx     #$00
	lda     $4016
	ldx     #$00
	and     #$01
	stx     tmp1
	ora     tmp1
	jeq     L00C6
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	ora     #$01
	ldy     #$01
	sta     (sp),y
L00C6:	ldy     #$00
	ldx     #$00
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	jmp     L00C4
L00C5:	ldy     #$01
	ldx     #$00
	lda     (sp),y
	jmp     L00BC
L00BC:	jsr     incsp2
	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ overlap (unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_overlap: near

.segment	"CODE"

	jsr     pusha
	ldy     #$07
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	ldy     #$07
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	ldy     #$05
	ldx     #$00
	lda     (sp),y
	jsr     tosuleax
	jeq     L00D5
	ldx     #$00
	lda     #$00
	jmp     L00D4
L00D5:	ldy     #$03
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	ldy     #$09
	ldx     #$00
	lda     (sp),y
	jsr     tosuleax
	jeq     L00D8
	ldx     #$00
	lda     #$00
	jmp     L00D4
L00D8:	ldy     #$06
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	ldy     #$06
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	jsr     tosuleax
	jeq     L00DB
	ldx     #$00
	lda     #$00
	jmp     L00D4
L00DB:	ldy     #$02
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	ldy     #$08
	ldx     #$00
	lda     (sp),y
	jsr     tosuleax
	jeq     L00DE
	ldx     #$00
	lda     #$00
	jmp     L00D4
L00DE:	ldx     #$00
	lda     #$01
	jmp     L00D4
L00D4:	jsr     incsp8
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ step_walk (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_step_walk: near

.segment	"CODE"

	ldx     #$00
	inc     _moveWait
	lda     _moveWait
	ldx     #$00
	lda     _moveWait
	cmp     #$07
	lda     #$00
	ldx     #$00
	rol     a
	jeq     L00E4
	ldx     #$00
	inc     _moved
	lda     _moved
	ldx     #$00
	lda     #$00
	sta     _moveWait
L00E4:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ update_player (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_update_player: near

.segment	"CODE"

	ldx     #$00
	lda     _pad
	ldx     #$00
	and     #$08
	stx     tmp1
	ora     tmp1
	jeq     L00ED
	lda     _jump
	jeq     L00ED
	ldx     #$00
	lda     _jmptime
	cmp     #$00
	jsr     booleq
	jne     L00EB
L00ED:	ldx     #$00
	lda     #$00
	jeq     L00EE
L00EB:	ldx     #$00
	lda     #$01
L00EE:	jeq     L00EA
	ldx     #$00
	lda     _y
	sec
	sbc     #$03
	sta     _y
	ldx     #$00
	lda     #$0F
	sta     _jmptime
L00EA:	ldx     #$00
	lda     _pad
	ldx     #$00
	and     #$04
	stx     tmp1
	ora     tmp1
	jeq     L00F6
	ldx     #$00
	lda     _y
	cmp     #$B0
	jsr     boolult
	jne     L00F4
L00F6:	ldx     #$00
	lda     #$00
	jeq     L00F7
L00F4:	ldx     #$00
	lda     #$01
L00F7:	jeq     L00F3
	ldx     #$00
	inc     _y
	lda     _y
L00F3:	ldx     #$00
	lda     _pad
	ldx     #$00
	and     #$02
	stx     tmp1
	ora     tmp1
	jeq     L00F9
	ldx     #$00
	dec     _x
	lda     _x
	ldx     #$00
	lda     #$40
	sta     _plrdir
	jsr     _step_walk
L00F9:	ldx     #$00
	lda     _pad
	ldx     #$00
	and     #$01
	stx     tmp1
	ora     tmp1
	jeq     L00FF
	ldx     #$00
	inc     _x
	lda     _x
	ldx     #$00
	lda     #$00
	sta     _plrdir
	jsr     _step_walk
L00FF:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ apply_gravity (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_apply_gravity: near

.segment	"CODE"

	ldx     #$00
	lda     _y
	cmp     #$B0
	jsr     boolult
	jeq     L0106
	ldx     #$00
	lda     #$00
	sta     _jump
	lda     _jmptime
	jeq     L010A
	ldx     #$00
	dec     _jmptime
	lda     _jmptime
	ldx     #$00
	lda     _y
	sec
	sbc     #$03
	sta     _y
	jmp     L010F
L010A:	ldx     #$00
	lda     #$03
	clc
	adc     _y
	sta     _y
L010F:	jmp     L0112
L0106:	ldx     #$00
	lda     #$01
	sta     _jump
L0112:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ patrol_enemy (__near__ unsigned char *, __near__ unsigned char *, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_patrol_enemy: near

.segment	"CODE"

	jsr     pusha
	ldy     #$03
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jeq     L0116
	ldy     #$05
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	ldx     #$00
	lda     #$01
	clc
	adc     (ptr1),y
	sta     (ptr1),y
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	jsr     tosugeax
	jeq     L0119
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staspidx
L0119:	jmp     L011F
L0116:	ldy     #$05
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	ldx     #$00
	lda     (ptr1),y
	sec
	sbc     #$01
	sta     (ptr1),y
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	jsr     tosuleax
	jeq     L011F
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$01
	ldy     #$00
	jsr     staspidx
L011F:	jsr     incsp6
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ update_enemies (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_update_enemies: near

.segment	"CODE"

	ldx     #$00
	inc     _enemy_timer
	lda     _enemy_timer
	ldx     #$00
	lda     _enemy_timer
	jsr     pushax
	ldx     #$00
	lda     _enemy_speed
	jsr     tosultax
	jeq     L0125
	jmp     L0123
L0125:	ldx     #$00
	lda     #$00
	sta     _enemy_timer
	lda     #<(_enemy1_x)
	ldx     #>(_enemy1_x)
	jsr     pushax
	lda     #<(_enemy1_dir)
	ldx     #>(_enemy1_dir)
	jsr     pushax
	lda     _enemy1_left
	jsr     pusha
	lda     _enemy1_right
	jsr     _patrol_enemy
	lda     #<(_enemy2_x)
	ldx     #>(_enemy2_x)
	jsr     pushax
	lda     #<(_enemy2_dir)
	ldx     #>(_enemy2_dir)
	jsr     pushax
	lda     _enemy2_left
	jsr     pusha
	lda     _enemy2_right
	jsr     _patrol_enemy
L0123:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ collect_items (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_collect_items: near

.segment	"CODE"

	jsr     decsp1
	ldx     #$00
	lda     #$00
	ldy     #$00
	sta     (sp),y
L0134:	ldy     #$00
	ldx     #$00
	lda     (sp),y
	cmp     #$04
	jsr     boolult
	jne     L0137
	jmp     L0135
L0137:	lda     #<(_gem_collected)
	ldx     #>(_gem_collected)
	ldy     #$00
	clc
	adc     (sp),y
	bcc     L013F
	inx
L013F:	ldy     #$00
	jsr     ldauidx
	jsr     bnega
	jeq     L0140
	lda     _x
	jsr     pusha
	lda     _y
	jsr     pusha
	lda     #$10
	jsr     pusha
	lda     #$20
	jsr     pusha
	lda     #<(_gem_x)
	ldx     #>(_gem_x)
	ldy     #$04
	clc
	adc     (sp),y
	bcc     L0147
	inx
L0147:	ldy     #$00
	jsr     ldauidx
	jsr     pusha
	lda     #<(_gem_y)
	ldx     #>(_gem_y)
	ldy     #$05
	clc
	adc     (sp),y
	bcc     L014A
	inx
L014A:	ldy     #$00
	jsr     ldauidx
	jsr     pusha
	lda     #$08
	jsr     pusha
	lda     #$08
	jsr     _overlap
	tax
	jne     L013D
L0140:	ldx     #$00
	lda     #$00
	jeq     L014D
L013D:	ldx     #$00
	lda     #$01
L014D:	jeq     L0136
	lda     #<(_gem_collected)
	ldx     #>(_gem_collected)
	ldy     #$00
	clc
	adc     (sp),y
	bcc     L0150
	inx
L0150:	jsr     pushax
	ldx     #$00
	lda     #$01
	ldy     #$00
	jsr     staspidx
	ldx     #$00
	inc     _score
	lda     _score
L0136:	ldy     #$00
	ldx     #$00
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	jmp     L0134
L0135:	ldx     #$00
	lda     _heart_collected
	jsr     bnega
	jeq     L0155
	lda     _x
	jsr     pusha
	lda     _y
	jsr     pusha
	lda     #$10
	jsr     pusha
	lda     #$20
	jsr     pusha
	lda     _heart_x
	jsr     pusha
	lda     _heart_y
	jsr     pusha
	lda     #$08
	jsr     pusha
	lda     #$08
	jsr     _overlap
	tax
	jne     L0154
L0155:	ldx     #$00
	lda     #$00
	jeq     L015E
L0154:	ldx     #$00
	lda     #$01
L015E:	jeq     L0153
	ldx     #$00
	lda     #$01
	sta     _heart_collected
L0153:	jsr     incsp1
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ draw_sprite (unsigned char, unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_sprite: near

.segment	"CODE"

	jsr     pusha
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	sta     $2004
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	sta     $2004
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	sta     $2004
	ldy     #$00
	ldx     #$00
	lda     (sp),y
	sta     $2004
	jsr     incsp4
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ draw_player (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_player: near

.segment	"CODE"

	jsr     decsp3
	ldx     #$00
	lda     _moved
	ldx     #$00
	and     #$03
	jsr     aslax3
	clc
	adc     #<(_anim_tiles)
	tay
	txa
	adc     #>(_anim_tiles)
	tax
	tya
	jsr     pushax
	ldx     #$00
	lda     _plrdir
	cmp     #$40
	jsr     booleq
	jeq     L0171
	ldx     #$00
	lda     _x
	jsr     incax8
	ldx     #$00
	ldy     #$03
	sta     (sp),y
	ldx     #$00
	lda     _x
	ldy     #$02
	sta     (sp),y
	jmp     L0177
L0171:	ldx     #$00
	lda     _x
	ldy     #$03
	sta     (sp),y
	ldx     #$00
	lda     _x
	jsr     incax8
	ldx     #$00
	ldy     #$02
	sta     (sp),y
L0177:	ldx     #$00
	lda     #$00
	ldy     #$04
	sta     (sp),y
L017C:	ldy     #$04
	ldx     #$00
	lda     (sp),y
	cmp     #$04
	jsr     boolult
	jne     L017F
	jmp     L017D
L017F:	ldx     #$00
	lda     _y
	jsr     pushax
	ldy     #$06
	ldx     #$00
	lda     (sp),y
	jsr     aslax3
	jsr     tosaddax
	ldx     #$00
	jsr     pusha
	ldy     #$02
	jsr     ldaxysp
	jsr     pushax
	ldy     #$07
	ldx     #$00
	lda     (sp),y
	jsr     aslax1
	jsr     tosaddax
	ldy     #$00
	jsr     ldauidx
	jsr     pusha
	lda     _plrdir
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     _draw_sprite
	ldx     #$00
	lda     _y
	jsr     pushax
	ldy     #$06
	ldx     #$00
	lda     (sp),y
	jsr     aslax3
	jsr     tosaddax
	ldx     #$00
	jsr     pusha
	ldy     #$02
	jsr     ldaxysp
	jsr     pushax
	ldy     #$07
	ldx     #$00
	lda     (sp),y
	jsr     aslax1
	jsr     incax1
	jsr     tosaddax
	ldy     #$00
	jsr     ldauidx
	jsr     pusha
	lda     _plrdir
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     _draw_sprite
	ldy     #$04
	ldx     #$00
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	jmp     L017C
L017D:	jsr     incsp5
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ draw_enemy (unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_enemy: near

.segment	"CODE"

	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$09
	lda     (sp),y
	jsr     _draw_sprite
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$09
	ldx     #$00
	lda     (sp),y
	jsr     incax8
	ldx     #$00
	jsr     _draw_sprite
	ldy     #$05
	ldx     #$00
	lda     (sp),y
	jsr     incax8
	ldx     #$00
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$09
	lda     (sp),y
	jsr     _draw_sprite
	ldy     #$05
	ldx     #$00
	lda     (sp),y
	jsr     incax8
	ldx     #$00
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$09
	ldx     #$00
	lda     (sp),y
	jsr     incax8
	ldx     #$00
	jsr     _draw_sprite
	jsr     incsp7
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ draw_items (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_items: near

.segment	"CODE"

	jsr     decsp1
	ldx     #$00
	lda     #$00
	ldy     #$00
	sta     (sp),y
L01A9:	ldy     #$00
	ldx     #$00
	lda     (sp),y
	cmp     #$04
	jsr     boolult
	jne     L01AC
	jmp     L01AA
L01AC:	lda     #<(_gem_collected)
	ldx     #>(_gem_collected)
	ldy     #$00
	clc
	adc     (sp),y
	bcc     L01B4
	inx
L01B4:	ldy     #$00
	jsr     ldauidx
	jeq     L01B5
	ldx     #$00
	lda     #$FF
	jmp     L01B7
L01B5:	lda     #<(_gem_y)
	ldx     #>(_gem_y)
	ldy     #$00
	clc
	adc     (sp),y
	bcc     L01BA
	inx
L01BA:	ldy     #$00
	jsr     ldauidx
	ldx     #$00
L01B7:	ldx     #$00
	jsr     pusha
	lda     #$48
	jsr     pusha
	lda     #$03
	jsr     pusha
	lda     #<(_gem_collected)
	ldx     #>(_gem_collected)
	ldy     #$03
	clc
	adc     (sp),y
	bcc     L01BF
	inx
L01BF:	ldy     #$00
	jsr     ldauidx
	jeq     L01C0
	ldx     #$00
	lda     #$00
	jmp     L01C2
L01C0:	lda     #<(_gem_x)
	ldx     #>(_gem_x)
	ldy     #$03
	clc
	adc     (sp),y
	bcc     L01C5
	inx
L01C5:	ldy     #$00
	jsr     ldauidx
	ldx     #$00
L01C2:	ldx     #$00
	jsr     _draw_sprite
	ldy     #$00
	ldx     #$00
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	jmp     L01A9
L01AA:	lda     _heart_collected
	jeq     L01C8
	ldx     #$00
	lda     #$FF
	jmp     L01CA
L01C8:	ldx     #$00
	lda     _heart_y
	ldx     #$00
L01CA:	ldx     #$00
	jsr     pusha
	lda     #$49
	jsr     pusha
	lda     #$03
	jsr     pusha
	lda     _heart_collected
	jeq     L01CF
	ldx     #$00
	lda     #$00
	jmp     L01D1
L01CF:	ldx     #$00
	lda     _heart_x
	ldx     #$00
L01D1:	ldx     #$00
	jsr     _draw_sprite
	jsr     incsp1
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ game_update (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_game_update: near

.segment	"CODE"

	jsr     _read_controller
	sta     _pad
	jsr     _update_player
	jsr     _apply_gravity
	jsr     _update_enemies
	jsr     _collect_items
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ game_draw (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_game_draw: near

.segment	"CODE"

	jsr     _waitvsync
	jsr     _reset_scroll
	ldx     #$00
	lda     #$00
	sta     $2003
	jsr     _draw_player
	lda     _enemy1_x
	jsr     pusha
	lda     _enemy1_y
	jsr     pusha
	lda     #$40
	jsr     pusha
	lda     #$41
	jsr     pusha
	lda     #$50
	jsr     pusha
	lda     #$51
	jsr     pusha
	lda     #$01
	jsr     _draw_enemy
	lda     _enemy2_x
	jsr     pusha
	lda     _enemy2_y
	jsr     pusha
	lda     #$44
	jsr     pusha
	lda     #$45
	jsr     pusha
	lda     #$54
	jsr     pusha
	lda     #$55
	jsr     pusha
	lda     #$02
	jsr     _draw_enemy
	jsr     _draw_items
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     _init_player
	jsr     _init_game
	jmp     L01F7
L01F5:	jsr     _game_update
	jsr     _game_draw
L01F7:	jmp     L01F5
	rts

.endproc
