;
; File generated by cc65 v 2.18 - Debian 2.19-2
;
	.fopt		compiler,"cc65 v 2.18 - Debian 2.19-2"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_waitvsync
	.import		_load_background
	.export		_main

.segment	"RODATA"

_anim_tiles:
	.byte	$01
	.byte	$02
	.byte	$11
	.byte	$12
	.byte	$21
	.byte	$22
	.byte	$31
	.byte	$32
	.byte	$09
	.byte	$0A
	.byte	$19
	.byte	$1A
	.byte	$29
	.byte	$2A
	.byte	$39
	.byte	$3A
	.byte	$01
	.byte	$02
	.byte	$11
	.byte	$12
	.byte	$21
	.byte	$22
	.byte	$31
	.byte	$32
	.byte	$0B
	.byte	$0C
	.byte	$1B
	.byte	$1C
	.byte	$2B
	.byte	$2C
	.byte	$3B
	.byte	$3C

.segment	"BSS"

_x:
	.res	1,$00
_y:
	.res	1,$00
_pad:
	.res	1,$00
_jump:
	.res	1,$00
_jmptime:
	.res	1,$00
_plrdir:
	.res	1,$00
_moved:
	.res	1,$00
_moveWait:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ ppu_seek (unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_ppu_seek: near

.segment	"CODE"

	jsr     pusha
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	sta     $2006
	ldy     #$00
	ldx     #$00
	lda     (sp),y
	sta     $2006
	jsr     incsp2
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ reset_scroll (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_reset_scroll: near

.segment	"CODE"

	ldx     #$00
	lda     #$00
	sta     $2005
	ldx     #$00
	lda     #$00
	sta     $2005
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ write_palettes (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_write_palettes: near

.segment	"CODE"

	lda     #$3F
	jsr     pusha
	lda     #$00
	jsr     _ppu_seek
	ldx     #$00
	lda     #$21
	sta     $2007
	ldx     #$00
	lda     #$29
	sta     $2007
	ldx     #$00
	lda     #$19
	sta     $2007
	ldx     #$00
	lda     #$07
	sta     $2007
	lda     #$3F
	jsr     pusha
	lda     #$05
	jsr     _ppu_seek
	ldx     #$00
	lda     #$00
	sta     $2007
	ldx     #$00
	lda     #$10
	sta     $2007
	ldx     #$00
	lda     #$2D
	sta     $2007
	lda     #$3F
	jsr     pusha
	lda     #$11
	jsr     _ppu_seek
	ldx     #$00
	lda     #$30
	sta     $2007
	ldx     #$00
	lda     #$27
	sta     $2007
	ldx     #$00
	lda     #$17
	sta     $2007
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ init_player (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_player: near

.segment	"CODE"

	ldx     #$00
	lda     #$3C
	sta     _x
	ldx     #$00
	lda     #$B0
	sta     _y
	ldx     #$00
	lda     #$00
	sta     _pad
	ldx     #$00
	lda     #$01
	sta     _jump
	ldx     #$00
	lda     #$00
	sta     _jmptime
	ldx     #$00
	lda     #$00
	sta     _plrdir
	ldx     #$00
	lda     #$00
	sta     _moved
	ldx     #$00
	lda     #$00
	sta     _moveWait
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ init_game (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_game: near

.segment	"CODE"

	jsr     _waitvsync
	ldx     #$00
	lda     #$00
	sta     $2001
	jsr     _write_palettes
	jsr     _load_background
	ldx     #$00
	lda     #$10
	sta     $2000
	jsr     _reset_scroll
	ldx     #$00
	lda     #$1E
	sta     $2001
	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ read_controller (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_read_controller: near

.segment	"CODE"

	lda     #$00
	jsr     pusha
	jsr     decsp1
	ldx     #$00
	lda     #$01
	sta     $4016
	ldx     #$00
	lda     #$00
	sta     $4016
	ldx     #$00
	lda     #$00
	ldy     #$00
	sta     (sp),y
L0081:	ldy     #$00
	ldx     #$00
	lda     (sp),y
	cmp     #$08
	jsr     boolult
	jne     L0084
	jmp     L0082
L0084:	ldy     #$01
	ldx     #$00
	lda     (sp),y
	jsr     shlax1
	ldy     #$01
	sta     (sp),y
	ldx     #$00
	lda     $4016
	ldx     #$00
	and     #$01
	stx     tmp1
	ora     tmp1
	jeq     L0083
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	ora     #$01
	ldy     #$01
	sta     (sp),y
L0083:	ldy     #$00
	ldx     #$00
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	jmp     L0081
L0082:	ldy     #$01
	ldx     #$00
	lda     (sp),y
	jmp     L0079
L0079:	jsr     incsp2
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ step_walk (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_step_walk: near

.segment	"CODE"

	ldx     #$00
	inc     _moveWait
	lda     _moveWait
	ldx     #$00
	lda     _moveWait
	cmp     #$07
	lda     #$00
	ldx     #$00
	rol     a
	jeq     L0093
	ldx     #$00
	inc     _moved
	lda     _moved
	ldx     #$00
	lda     #$00
	sta     _moveWait
L0093:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ update_player (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_update_player: near

.segment	"CODE"

	ldx     #$00
	lda     _pad
	ldx     #$00
	and     #$08
	stx     tmp1
	ora     tmp1
	jeq     L009C
	lda     _jump
	jeq     L009C
	ldx     #$00
	lda     _jmptime
	cmp     #$00
	jsr     booleq
	jne     L009A
L009C:	ldx     #$00
	lda     #$00
	jeq     L009D
L009A:	ldx     #$00
	lda     #$01
L009D:	jeq     L0099
	ldx     #$00
	lda     _y
	sec
	sbc     #$03
	sta     _y
	ldx     #$00
	lda     #$0F
	sta     _jmptime
L0099:	ldx     #$00
	lda     _pad
	ldx     #$00
	and     #$04
	stx     tmp1
	ora     tmp1
	jeq     L00A5
	ldx     #$00
	lda     _y
	cmp     #$B0
	jsr     boolult
	jne     L00A3
L00A5:	ldx     #$00
	lda     #$00
	jeq     L00A6
L00A3:	ldx     #$00
	lda     #$01
L00A6:	jeq     L00A2
	ldx     #$00
	inc     _y
	lda     _y
L00A2:	ldx     #$00
	lda     _pad
	ldx     #$00
	and     #$02
	stx     tmp1
	ora     tmp1
	jeq     L00A8
	ldx     #$00
	dec     _x
	lda     _x
	ldx     #$00
	lda     #$40
	sta     _plrdir
	jsr     _step_walk
L00A8:	ldx     #$00
	lda     _pad
	ldx     #$00
	and     #$01
	stx     tmp1
	ora     tmp1
	jeq     L00AE
	ldx     #$00
	inc     _x
	lda     _x
	ldx     #$00
	lda     #$00
	sta     _plrdir
	jsr     _step_walk
L00AE:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ apply_gravity (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_apply_gravity: near

.segment	"CODE"

	ldx     #$00
	lda     _y
	cmp     #$B0
	jsr     boolult
	jeq     L00B5
	ldx     #$00
	lda     #$00
	sta     _jump
	lda     _jmptime
	jeq     L00B9
	ldx     #$00
	dec     _jmptime
	lda     _jmptime
	ldx     #$00
	lda     _y
	sec
	sbc     #$03
	sta     _y
	jmp     L00BE
L00B9:	ldx     #$00
	lda     #$03
	clc
	adc     _y
	sta     _y
L00BE:	jmp     L00C1
L00B5:	ldx     #$00
	lda     #$01
	sta     _jump
L00C1:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ draw_sprite (unsigned char, unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_sprite: near

.segment	"CODE"

	jsr     pusha
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	sta     $2004
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	sta     $2004
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	sta     $2004
	ldy     #$00
	ldx     #$00
	lda     (sp),y
	sta     $2004
	jsr     incsp4
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ draw_player (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_player: near

.segment	"CODE"

	jsr     decsp3
	ldx     #$00
	lda     _moved
	ldx     #$00
	and     #$03
	jsr     aslax3
	clc
	adc     #<(_anim_tiles)
	tay
	txa
	adc     #>(_anim_tiles)
	tax
	tya
	jsr     pushax
	ldx     #$00
	lda     _plrdir
	cmp     #$40
	jsr     booleq
	jeq     L00D4
	ldx     #$00
	lda     _x
	jsr     incax8
	ldx     #$00
	ldy     #$03
	sta     (sp),y
	ldx     #$00
	lda     _x
	ldy     #$02
	sta     (sp),y
	jmp     L00DA
L00D4:	ldx     #$00
	lda     _x
	ldy     #$03
	sta     (sp),y
	ldx     #$00
	lda     _x
	jsr     incax8
	ldx     #$00
	ldy     #$02
	sta     (sp),y
L00DA:	ldx     #$00
	lda     #$00
	sta     $2003
	ldx     #$00
	lda     #$00
	ldy     #$04
	sta     (sp),y
L00E2:	ldy     #$04
	ldx     #$00
	lda     (sp),y
	cmp     #$04
	jsr     boolult
	jne     L00E5
	jmp     L00E3
L00E5:	ldx     #$00
	lda     _y
	jsr     pushax
	ldy     #$06
	ldx     #$00
	lda     (sp),y
	jsr     aslax3
	jsr     tosaddax
	ldx     #$00
	jsr     pusha
	ldy     #$02
	jsr     ldaxysp
	jsr     pushax
	ldy     #$07
	ldx     #$00
	lda     (sp),y
	jsr     aslax1
	jsr     tosaddax
	ldy     #$00
	jsr     ldauidx
	jsr     pusha
	lda     _plrdir
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     _draw_sprite
	ldx     #$00
	lda     _y
	jsr     pushax
	ldy     #$06
	ldx     #$00
	lda     (sp),y
	jsr     aslax3
	jsr     tosaddax
	ldx     #$00
	jsr     pusha
	ldy     #$02
	jsr     ldaxysp
	jsr     pushax
	ldy     #$07
	ldx     #$00
	lda     (sp),y
	jsr     aslax1
	jsr     incax1
	jsr     tosaddax
	ldy     #$00
	jsr     ldauidx
	jsr     pusha
	lda     _plrdir
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     _draw_sprite
	ldy     #$04
	ldx     #$00
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	jmp     L00E2
L00E3:	jsr     incsp5
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ game_update (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_game_update: near

.segment	"CODE"

	jsr     _read_controller
	sta     _pad
	jsr     _update_player
	jsr     _apply_gravity
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ game_draw (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_game_draw: near

.segment	"CODE"

	jsr     _waitvsync
	jsr     _reset_scroll
	jsr     _draw_player
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     _init_player
	jsr     _init_game
	jmp     L0107
L0105:	jsr     _game_update
	jsr     _game_draw
L0107:	jmp     L0105
	rts

.endproc

