;
; File generated by cc65 v 2.18 - Debian 2.19-2
;
	.fopt		compiler,"cc65 v 2.18 - Debian 2.19-2"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_waitvsync
	.import		_load_background
	.export		_main

.segment	"DATA"

_game_state:
	.byte	$00
_enemy1_x:
	.byte	$96
_enemy1_y:
	.byte	$C0
_enemy1_dir:
	.byte	$01
_enemy1_left:
	.byte	$78
_enemy1_right:
	.byte	$C8
_enemy2_x:
	.byte	$50
_enemy2_y:
	.byte	$80
_enemy2_dir:
	.byte	$01
_enemy2_left:
	.byte	$40
_enemy2_right:
	.byte	$70
_enemy_timer:
	.byte	$00
_enemy_speed:
	.byte	$03
_npc_x:
	.byte	$28
_npc_y:
	.byte	$C0
_gem_x:
	.byte	$64
	.byte	$8C
	.byte	$B4
	.byte	$58
_gem_y:
	.byte	$A8
	.byte	$A8
	.byte	$A8
	.byte	$68
_gem_collected:
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
_heart_x:
	.byte	$B0
_heart_y:
	.byte	$68
_heart_collected:
	.byte	$00
_score:
	.byte	$00

.segment	"RODATA"

_anim_tiles:
	.byte	$01
	.byte	$02
	.byte	$11
	.byte	$12
	.byte	$21
	.byte	$22
	.byte	$31
	.byte	$32
	.byte	$09
	.byte	$0A
	.byte	$19
	.byte	$1A
	.byte	$29
	.byte	$2A
	.byte	$39
	.byte	$3A
	.byte	$01
	.byte	$02
	.byte	$11
	.byte	$12
	.byte	$21
	.byte	$22
	.byte	$31
	.byte	$32
	.byte	$0B
	.byte	$0C
	.byte	$1B
	.byte	$1C
	.byte	$2B
	.byte	$2C
	.byte	$3B
	.byte	$3C
_msg_hello:
	.byte	$17
	.byte	$14
	.byte	$1B
	.byte	$1B
	.byte	$1E
	.byte	$34
	.byte	$17
	.byte	$14
	.byte	$21
	.byte	$1E
	.byte	$35
	.byte	$00

.segment	"BSS"

_x:
	.res	1,$00
_y:
	.res	1,$00
_pad:
	.res	1,$00
_prev_pad:
	.res	1,$00
_jump:
	.res	1,$00
_jmptime:
	.res	1,$00
_plrdir:
	.res	1,$00
_moved:
	.res	1,$00
_moveWait:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ ppu_seek (unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_ppu_seek: near

.segment	"CODE"

	jsr     pusha
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	sta     $2006
	ldy     #$00
	ldx     #$00
	lda     (sp),y
	sta     $2006
	jsr     incsp2
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ reset_scroll (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_reset_scroll: near

.segment	"CODE"

	ldx     #$00
	lda     #$00
	sta     $2005
	ldx     #$00
	lda     #$00
	sta     $2005
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ set_cell (unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_set_cell: near

.segment	"CODE"

	jsr     pusha
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	ldx     #$00
	jsr     shlax4
	jsr     shlax1
	jsr     pushax
	ldx     #$20
	lda     #$00
	jsr     tosaddax
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	ldx     #$00
	sta     $2006
	ldy     #$01
	jsr     ldaxysp
	ldx     #$00
	ldx     #$00
	sta     $2006
	jsr     incsp4
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ write_palettes (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_write_palettes: near

.segment	"CODE"

	lda     #$3F
	jsr     pusha
	lda     #$00
	jsr     _ppu_seek
	ldx     #$00
	lda     #$21
	sta     $2007
	ldx     #$00
	lda     #$29
	sta     $2007
	ldx     #$00
	lda     #$19
	sta     $2007
	ldx     #$00
	lda     #$07
	sta     $2007
	lda     #$3F
	jsr     pusha
	lda     #$05
	jsr     _ppu_seek
	ldx     #$00
	lda     #$00
	sta     $2007
	ldx     #$00
	lda     #$10
	sta     $2007
	ldx     #$00
	lda     #$2D
	sta     $2007
	lda     #$3F
	jsr     pusha
	lda     #$11
	jsr     _ppu_seek
	ldx     #$00
	lda     #$30
	sta     $2007
	ldx     #$00
	lda     #$27
	sta     $2007
	ldx     #$00
	lda     #$17
	sta     $2007
	lda     #$3F
	jsr     pusha
	lda     #$15
	jsr     _ppu_seek
	ldx     #$00
	lda     #$1A
	sta     $2007
	ldx     #$00
	lda     #$30
	sta     $2007
	ldx     #$00
	lda     #$0A
	sta     $2007
	lda     #$3F
	jsr     pusha
	lda     #$19
	jsr     _ppu_seek
	ldx     #$00
	lda     #$30
	sta     $2007
	ldx     #$00
	lda     #$16
	sta     $2007
	ldx     #$00
	lda     #$07
	sta     $2007
	lda     #$3F
	jsr     pusha
	lda     #$1D
	jsr     _ppu_seek
	ldx     #$00
	lda     #$16
	sta     $2007
	ldx     #$00
	lda     #$36
	sta     $2007
	ldx     #$00
	lda     #$06
	sta     $2007
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ init_player (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_player: near

.segment	"CODE"

	ldx     #$00
	lda     #$3C
	sta     _x
	ldx     #$00
	lda     #$B0
	sta     _y
	ldx     #$00
	lda     #$00
	sta     _pad
	ldx     #$00
	lda     #$00
	sta     _prev_pad
	ldx     #$00
	lda     #$01
	sta     _jump
	ldx     #$00
	lda     #$00
	sta     _jmptime
	ldx     #$00
	lda     #$00
	sta     _plrdir
	ldx     #$00
	lda     #$00
	sta     _moved
	ldx     #$00
	lda     #$00
	sta     _moveWait
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ init_game (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_game: near

.segment	"CODE"

	jsr     _waitvsync
	ldx     #$00
	lda     #$00
	sta     $2001
	jsr     _write_palettes
	jsr     _load_background
	ldx     #$00
	lda     #$10
	sta     $2000
	jsr     _reset_scroll
	ldx     #$00
	lda     #$1E
	sta     $2001
	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ read_controller (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_read_controller: near

.segment	"CODE"

	lda     #$00
	jsr     pusha
	jsr     decsp1
	ldx     #$00
	lda     #$01
	sta     $4016
	ldx     #$00
	lda     #$00
	sta     $4016
	ldx     #$00
	lda     #$00
	ldy     #$00
	sta     (sp),y
L00E0:	ldy     #$00
	ldx     #$00
	lda     (sp),y
	cmp     #$08
	jsr     boolult
	jne     L00E3
	jmp     L00E1
L00E3:	ldy     #$01
	ldx     #$00
	lda     (sp),y
	jsr     shlax1
	ldy     #$01
	sta     (sp),y
	ldx     #$00
	lda     $4016
	ldx     #$00
	and     #$01
	stx     tmp1
	ora     tmp1
	jeq     L00E2
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	ora     #$01
	ldy     #$01
	sta     (sp),y
L00E2:	ldy     #$00
	ldx     #$00
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	jmp     L00E0
L00E1:	ldy     #$01
	ldx     #$00
	lda     (sp),y
	jmp     L00D8
L00D8:	jsr     incsp2
	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ overlap (unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_overlap: near

.segment	"CODE"

	jsr     pusha
	ldy     #$07
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	ldy     #$07
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	ldy     #$05
	ldx     #$00
	lda     (sp),y
	jsr     tosuleax
	jeq     L00F1
	ldx     #$00
	lda     #$00
	jmp     L00F0
L00F1:	ldy     #$03
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	ldy     #$09
	ldx     #$00
	lda     (sp),y
	jsr     tosuleax
	jeq     L00F4
	ldx     #$00
	lda     #$00
	jmp     L00F0
L00F4:	ldy     #$06
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	ldy     #$06
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	jsr     tosuleax
	jeq     L00F7
	ldx     #$00
	lda     #$00
	jmp     L00F0
L00F7:	ldy     #$02
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	ldy     #$08
	ldx     #$00
	lda     (sp),y
	jsr     tosuleax
	jeq     L00FA
	ldx     #$00
	lda     #$00
	jmp     L00F0
L00FA:	ldx     #$00
	lda     #$01
	jmp     L00F0
L00F0:	jsr     incsp8
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ clear_text_row (unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_clear_text_row: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp1
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     _set_cell
	ldx     #$00
	lda     #$00
	ldy     #$00
	sta     (sp),y
L0102:	ldy     #$00
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	jsr     tosultax
	jne     L0105
	jmp     L0103
L0105:	ldx     #$00
	lda     #$00
	sta     $2007
	ldy     #$00
	ldx     #$00
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	jmp     L0102
L0103:	jsr     incsp4
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ draw_text (unsigned char, unsigned char, __near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_text: near

.segment	"CODE"

	jsr     pushax
	lda     #$00
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	jsr     _set_cell
	jmp     L0114
L0112:	ldy     #$02
	jsr     ldaxysp
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	ldy     #$00
	jsr     ldauidx
	sta     $2007
	ldy     #$00
	ldx     #$00
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
L0114:	ldy     #$02
	jsr     ldaxysp
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	ldy     #$00
	jsr     ldauidx
	cmp     #$00
	jsr     boolne
	jne     L0112
	jsr     incsp5
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ show_dialogue (__near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_show_dialogue: near

.segment	"CODE"

	jsr     pushax
	jsr     _waitvsync
	ldx     #$00
	lda     #$00
	sta     $2001
	lda     #$02
	jsr     pusha
	lda     #$04
	jsr     pusha
	lda     #$18
	jsr     _clear_text_row
	lda     #$02
	jsr     pusha
	lda     #$04
	jsr     pusha
	ldy     #$03
	jsr     ldaxysp
	jsr     _draw_text
	jsr     _reset_scroll
	ldx     #$00
	lda     #$1E
	sta     $2001
	jsr     incsp2
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ hide_dialogue (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_hide_dialogue: near

.segment	"CODE"

	jsr     _waitvsync
	ldx     #$00
	lda     #$00
	sta     $2001
	lda     #$02
	jsr     pusha
	lda     #$04
	jsr     pusha
	lda     #$18
	jsr     _clear_text_row
	jsr     _reset_scroll
	ldx     #$00
	lda     #$1E
	sta     $2001
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ step_walk (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_step_walk: near

.segment	"CODE"

	ldx     #$00
	inc     _moveWait
	lda     _moveWait
	ldx     #$00
	lda     _moveWait
	cmp     #$07
	lda     #$00
	ldx     #$00
	rol     a
	jeq     L013C
	ldx     #$00
	inc     _moved
	lda     _moved
	ldx     #$00
	lda     #$00
	sta     _moveWait
L013C:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ update_player (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_update_player: near

.segment	"CODE"

	ldx     #$00
	lda     _pad
	ldx     #$00
	and     #$08
	stx     tmp1
	ora     tmp1
	jeq     L0145
	lda     _jump
	jeq     L0145
	ldx     #$00
	lda     _jmptime
	cmp     #$00
	jsr     booleq
	jne     L0143
L0145:	ldx     #$00
	lda     #$00
	jeq     L0146
L0143:	ldx     #$00
	lda     #$01
L0146:	jeq     L0142
	ldx     #$00
	lda     _y
	sec
	sbc     #$03
	sta     _y
	ldx     #$00
	lda     #$0F
	sta     _jmptime
L0142:	ldx     #$00
	lda     _pad
	ldx     #$00
	and     #$04
	stx     tmp1
	ora     tmp1
	jeq     L014E
	ldx     #$00
	lda     _y
	cmp     #$B0
	jsr     boolult
	jne     L014C
L014E:	ldx     #$00
	lda     #$00
	jeq     L014F
L014C:	ldx     #$00
	lda     #$01
L014F:	jeq     L014B
	ldx     #$00
	inc     _y
	lda     _y
L014B:	ldx     #$00
	lda     _pad
	ldx     #$00
	and     #$02
	stx     tmp1
	ora     tmp1
	jeq     L0151
	ldx     #$00
	dec     _x
	lda     _x
	ldx     #$00
	lda     #$40
	sta     _plrdir
	jsr     _step_walk
L0151:	ldx     #$00
	lda     _pad
	ldx     #$00
	and     #$01
	stx     tmp1
	ora     tmp1
	jeq     L0157
	ldx     #$00
	inc     _x
	lda     _x
	ldx     #$00
	lda     #$00
	sta     _plrdir
	jsr     _step_walk
L0157:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ apply_gravity (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_apply_gravity: near

.segment	"CODE"

	ldx     #$00
	lda     _y
	cmp     #$B0
	jsr     boolult
	jeq     L015E
	ldx     #$00
	lda     #$00
	sta     _jump
	lda     _jmptime
	jeq     L0162
	ldx     #$00
	dec     _jmptime
	lda     _jmptime
	ldx     #$00
	lda     _y
	sec
	sbc     #$03
	sta     _y
	jmp     L0167
L0162:	ldx     #$00
	lda     #$03
	clc
	adc     _y
	sta     _y
L0167:	jmp     L016A
L015E:	ldx     #$00
	lda     #$01
	sta     _jump
L016A:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ patrol_enemy (__near__ unsigned char *, __near__ unsigned char *, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_patrol_enemy: near

.segment	"CODE"

	jsr     pusha
	ldy     #$03
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jeq     L016E
	ldy     #$05
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	ldx     #$00
	lda     #$01
	clc
	adc     (ptr1),y
	sta     (ptr1),y
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	jsr     tosugeax
	jeq     L0171
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staspidx
L0171:	jmp     L0177
L016E:	ldy     #$05
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	ldx     #$00
	lda     (ptr1),y
	sec
	sbc     #$01
	sta     (ptr1),y
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	jsr     tosuleax
	jeq     L0177
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$01
	ldy     #$00
	jsr     staspidx
L0177:	jsr     incsp6
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ update_enemies (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_update_enemies: near

.segment	"CODE"

	ldx     #$00
	inc     _enemy_timer
	lda     _enemy_timer
	ldx     #$00
	lda     _enemy_timer
	jsr     pushax
	ldx     #$00
	lda     _enemy_speed
	jsr     tosultax
	jeq     L017D
	jmp     L017B
L017D:	ldx     #$00
	lda     #$00
	sta     _enemy_timer
	lda     #<(_enemy1_x)
	ldx     #>(_enemy1_x)
	jsr     pushax
	lda     #<(_enemy1_dir)
	ldx     #>(_enemy1_dir)
	jsr     pushax
	lda     _enemy1_left
	jsr     pusha
	lda     _enemy1_right
	jsr     _patrol_enemy
	lda     #<(_enemy2_x)
	ldx     #>(_enemy2_x)
	jsr     pushax
	lda     #<(_enemy2_dir)
	ldx     #>(_enemy2_dir)
	jsr     pushax
	lda     _enemy2_left
	jsr     pusha
	lda     _enemy2_right
	jsr     _patrol_enemy
L017B:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ collect_items (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_collect_items: near

.segment	"CODE"

	jsr     decsp1
	ldx     #$00
	lda     #$00
	ldy     #$00
	sta     (sp),y
L018C:	ldy     #$00
	ldx     #$00
	lda     (sp),y
	cmp     #$04
	jsr     boolult
	jne     L018F
	jmp     L018D
L018F:	lda     #<(_gem_collected)
	ldx     #>(_gem_collected)
	ldy     #$00
	clc
	adc     (sp),y
	bcc     L0197
	inx
L0197:	ldy     #$00
	jsr     ldauidx
	jsr     bnega
	jeq     L0198
	lda     _x
	jsr     pusha
	lda     _y
	jsr     pusha
	lda     #$10
	jsr     pusha
	lda     #$20
	jsr     pusha
	lda     #<(_gem_x)
	ldx     #>(_gem_x)
	ldy     #$04
	clc
	adc     (sp),y
	bcc     L019F
	inx
L019F:	ldy     #$00
	jsr     ldauidx
	jsr     pusha
	lda     #<(_gem_y)
	ldx     #>(_gem_y)
	ldy     #$05
	clc
	adc     (sp),y
	bcc     L01A2
	inx
L01A2:	ldy     #$00
	jsr     ldauidx
	jsr     pusha
	lda     #$08
	jsr     pusha
	lda     #$08
	jsr     _overlap
	tax
	jne     L0195
L0198:	ldx     #$00
	lda     #$00
	jeq     L01A5
L0195:	ldx     #$00
	lda     #$01
L01A5:	jeq     L018E
	lda     #<(_gem_collected)
	ldx     #>(_gem_collected)
	ldy     #$00
	clc
	adc     (sp),y
	bcc     L01A8
	inx
L01A8:	jsr     pushax
	ldx     #$00
	lda     #$01
	ldy     #$00
	jsr     staspidx
	ldx     #$00
	inc     _score
	lda     _score
L018E:	ldy     #$00
	ldx     #$00
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	jmp     L018C
L018D:	ldx     #$00
	lda     _heart_collected
	jsr     bnega
	jeq     L01AD
	lda     _x
	jsr     pusha
	lda     _y
	jsr     pusha
	lda     #$10
	jsr     pusha
	lda     #$20
	jsr     pusha
	lda     _heart_x
	jsr     pusha
	lda     _heart_y
	jsr     pusha
	lda     #$08
	jsr     pusha
	lda     #$08
	jsr     _overlap
	tax
	jne     L01AC
L01AD:	ldx     #$00
	lda     #$00
	jeq     L01B6
L01AC:	ldx     #$00
	lda     #$01
L01B6:	jeq     L01AB
	ldx     #$00
	lda     #$01
	sta     _heart_collected
L01AB:	jsr     incsp1
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ update_playing (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_update_playing: near

.segment	"CODE"

	jsr     pusha
	lda     _x
	jsr     pusha
	lda     _y
	jsr     pusha
	lda     #$10
	jsr     pusha
	lda     #$20
	jsr     pusha
	ldx     #$00
	lda     _npc_x
	jsr     decax4
	ldx     #$00
	jsr     pusha
	lda     _npc_y
	jsr     pusha
	lda     #$18
	jsr     pusha
	lda     #$10
	jsr     _overlap
	tax
	jeq     L01C4
	ldy     #$00
	lda     (sp),y
	jne     L01BB
L01C4:	ldx     #$00
	lda     #$00
	jeq     L01C5
L01BB:	ldx     #$00
	lda     #$01
L01C5:	jeq     L01BA
	lda     #<(_msg_hello)
	ldx     #>(_msg_hello)
	jsr     _show_dialogue
	ldx     #$00
	lda     #$01
	sta     _game_state
	ldx     #$00
	lda     _pad
	sta     _prev_pad
	jmp     L01B9
L01BA:	jsr     _update_player
	jsr     _apply_gravity
	jsr     _update_enemies
	jsr     _collect_items
L01B9:	jsr     incsp1
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ update_dialogue (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_update_dialogue: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	lda     (sp),y
	jeq     L01D1
	jsr     _hide_dialogue
	ldx     #$00
	lda     #$00
	sta     _game_state
L01D1:	jsr     incsp1
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ draw_sprite (unsigned char, unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_sprite: near

.segment	"CODE"

	jsr     pusha
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	sta     $2004
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	sta     $2004
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	sta     $2004
	ldy     #$00
	ldx     #$00
	lda     (sp),y
	sta     $2004
	jsr     incsp4
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ draw_player (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_player: near

.segment	"CODE"

	jsr     decsp3
	ldx     #$00
	lda     _moved
	ldx     #$00
	and     #$03
	jsr     aslax3
	clc
	adc     #<(_anim_tiles)
	tay
	txa
	adc     #>(_anim_tiles)
	tax
	tya
	jsr     pushax
	ldx     #$00
	lda     _plrdir
	cmp     #$40
	jsr     booleq
	jeq     L01E6
	ldx     #$00
	lda     _x
	jsr     incax8
	ldx     #$00
	ldy     #$03
	sta     (sp),y
	ldx     #$00
	lda     _x
	ldy     #$02
	sta     (sp),y
	jmp     L01EC
L01E6:	ldx     #$00
	lda     _x
	ldy     #$03
	sta     (sp),y
	ldx     #$00
	lda     _x
	jsr     incax8
	ldx     #$00
	ldy     #$02
	sta     (sp),y
L01EC:	ldx     #$00
	lda     #$00
	ldy     #$04
	sta     (sp),y
L01F1:	ldy     #$04
	ldx     #$00
	lda     (sp),y
	cmp     #$04
	jsr     boolult
	jne     L01F4
	jmp     L01F2
L01F4:	ldx     #$00
	lda     _y
	jsr     pushax
	ldy     #$06
	ldx     #$00
	lda     (sp),y
	jsr     aslax3
	jsr     tosaddax
	ldx     #$00
	jsr     pusha
	ldy     #$02
	jsr     ldaxysp
	jsr     pushax
	ldy     #$07
	ldx     #$00
	lda     (sp),y
	jsr     aslax1
	jsr     tosaddax
	ldy     #$00
	jsr     ldauidx
	jsr     pusha
	lda     _plrdir
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     _draw_sprite
	ldx     #$00
	lda     _y
	jsr     pushax
	ldy     #$06
	ldx     #$00
	lda     (sp),y
	jsr     aslax3
	jsr     tosaddax
	ldx     #$00
	jsr     pusha
	ldy     #$02
	jsr     ldaxysp
	jsr     pushax
	ldy     #$07
	ldx     #$00
	lda     (sp),y
	jsr     aslax1
	jsr     incax1
	jsr     tosaddax
	ldy     #$00
	jsr     ldauidx
	jsr     pusha
	lda     _plrdir
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     _draw_sprite
	ldy     #$04
	ldx     #$00
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	jmp     L01F1
L01F2:	jsr     incsp5
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ draw_enemy (unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_enemy: near

.segment	"CODE"

	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$09
	lda     (sp),y
	jsr     _draw_sprite
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$09
	ldx     #$00
	lda     (sp),y
	jsr     incax8
	ldx     #$00
	jsr     _draw_sprite
	ldy     #$05
	ldx     #$00
	lda     (sp),y
	jsr     incax8
	ldx     #$00
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$09
	lda     (sp),y
	jsr     _draw_sprite
	ldy     #$05
	ldx     #$00
	lda     (sp),y
	jsr     incax8
	ldx     #$00
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$09
	ldx     #$00
	lda     (sp),y
	jsr     incax8
	ldx     #$00
	jsr     _draw_sprite
	jsr     incsp7
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ draw_npc (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_npc: near

.segment	"CODE"

	lda     _npc_y
	jsr     pusha
	lda     #$60
	jsr     pusha
	lda     #$02
	jsr     pusha
	lda     _npc_x
	jsr     _draw_sprite
	lda     _npc_y
	jsr     pusha
	lda     #$61
	jsr     pusha
	lda     #$02
	jsr     pusha
	ldx     #$00
	lda     _npc_x
	jsr     incax8
	ldx     #$00
	jsr     _draw_sprite
	ldx     #$00
	lda     _npc_y
	jsr     incax8
	ldx     #$00
	jsr     pusha
	lda     #$70
	jsr     pusha
	lda     #$02
	jsr     pusha
	lda     _npc_x
	jsr     _draw_sprite
	ldx     #$00
	lda     _npc_y
	jsr     incax8
	ldx     #$00
	jsr     pusha
	lda     #$71
	jsr     pusha
	lda     #$02
	jsr     pusha
	ldx     #$00
	lda     _npc_x
	jsr     incax8
	ldx     #$00
	jsr     _draw_sprite
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ draw_items (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_items: near

.segment	"CODE"

	jsr     decsp1
	ldx     #$00
	lda     #$00
	ldy     #$00
	sta     (sp),y
L0233:	ldy     #$00
	ldx     #$00
	lda     (sp),y
	cmp     #$04
	jsr     boolult
	jne     L0236
	jmp     L0234
L0236:	lda     #<(_gem_collected)
	ldx     #>(_gem_collected)
	ldy     #$00
	clc
	adc     (sp),y
	bcc     L023E
	inx
L023E:	ldy     #$00
	jsr     ldauidx
	jeq     L023F
	ldx     #$00
	lda     #$FF
	jmp     L0241
L023F:	lda     #<(_gem_y)
	ldx     #>(_gem_y)
	ldy     #$00
	clc
	adc     (sp),y
	bcc     L0244
	inx
L0244:	ldy     #$00
	jsr     ldauidx
	ldx     #$00
L0241:	ldx     #$00
	jsr     pusha
	lda     #$48
	jsr     pusha
	lda     #$03
	jsr     pusha
	lda     #<(_gem_collected)
	ldx     #>(_gem_collected)
	ldy     #$03
	clc
	adc     (sp),y
	bcc     L0249
	inx
L0249:	ldy     #$00
	jsr     ldauidx
	jeq     L024A
	ldx     #$00
	lda     #$00
	jmp     L024C
L024A:	lda     #<(_gem_x)
	ldx     #>(_gem_x)
	ldy     #$03
	clc
	adc     (sp),y
	bcc     L024F
	inx
L024F:	ldy     #$00
	jsr     ldauidx
	ldx     #$00
L024C:	ldx     #$00
	jsr     _draw_sprite
	ldy     #$00
	ldx     #$00
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	jmp     L0233
L0234:	lda     _heart_collected
	jeq     L0252
	ldx     #$00
	lda     #$FF
	jmp     L0254
L0252:	ldx     #$00
	lda     _heart_y
	ldx     #$00
L0254:	ldx     #$00
	jsr     pusha
	lda     #$49
	jsr     pusha
	lda     #$03
	jsr     pusha
	lda     _heart_collected
	jeq     L0259
	ldx     #$00
	lda     #$00
	jmp     L025B
L0259:	ldx     #$00
	lda     _heart_x
	ldx     #$00
L025B:	ldx     #$00
	jsr     _draw_sprite
	jsr     incsp1
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ game_update (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_game_update: near

.segment	"CODE"

	jsr     decsp1
	jsr     _read_controller
	sta     _pad
	ldx     #$00
	lda     _pad
	ldx     #$00
	and     #$80
	stx     tmp1
	ora     tmp1
	jeq     L0263
	ldx     #$00
	lda     _prev_pad
	ldx     #$00
	and     #$80
	jsr     bnegax
	jne     L0261
L0263:	ldx     #$00
	lda     #$00
	jeq     L0265
L0261:	ldx     #$00
	lda     #$01
L0265:	ldx     #$00
	ldy     #$00
	sta     (sp),y
	ldx     #$00
	lda     _game_state
	cmp     #$00
	jsr     booleq
	jeq     L0266
	ldy     #$00
	lda     (sp),y
	jsr     _update_playing
	jmp     L026A
L0266:	ldy     #$00
	lda     (sp),y
	jsr     _update_dialogue
L026A:	ldx     #$00
	lda     _pad
	sta     _prev_pad
	jsr     incsp1
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ game_draw (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_game_draw: near

.segment	"CODE"

	jsr     _waitvsync
	jsr     _reset_scroll
	ldx     #$00
	lda     #$00
	sta     $2003
	jsr     _draw_player
	jsr     _draw_npc
	lda     _enemy1_x
	jsr     pusha
	lda     _enemy1_y
	jsr     pusha
	lda     #$40
	jsr     pusha
	lda     #$41
	jsr     pusha
	lda     #$50
	jsr     pusha
	lda     #$51
	jsr     pusha
	lda     #$01
	jsr     _draw_enemy
	lda     _enemy2_x
	jsr     pusha
	lda     _enemy2_y
	jsr     pusha
	lda     #$44
	jsr     pusha
	lda     #$45
	jsr     pusha
	lda     #$54
	jsr     pusha
	lda     #$55
	jsr     pusha
	lda     #$02
	jsr     _draw_enemy
	jsr     _draw_items
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     _init_player
	jsr     _init_game
	jmp     L028D
L028B:	jsr     _game_update
	jsr     _game_draw
L028D:	jmp     L028B
	rts

.endproc

