"""Static build inputs shared by the HTTP and native build adapters."""

from __future__ import annotations

AUTO_SONGS_STUB_ASM = """\\
.export _audio_default_music:=audio_default_music
.export audio_default_music
audio_default_music:
\t.byte 1
\t.word @instruments
\t.word @samples-4
\t.word @song0ch0
\t.word @song0ch1
\t.word @song0ch2
\t.word @song0ch3
\t.word @song0ch4
\t.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
@instruments:
\t.byte 0
@samples:
@song0ch0:
@song0ch1:
@song0ch2:
@song0ch3:
@song0ch4:
\t.byte $00
@tempo_env_1_mid:
\t.byte 6, 6, 6, 6, $00
"""

AUTO_SFX_STUB_ASM = """\\
.export _audio_sfx_data:=audio_sfx_data
.export audio_sfx_data
audio_sfx_data:
\t.word @ntsc
\t.word @ntsc
@ntsc:
\t.byte $00, $00
"""

ASM_MAKEFILE = """\\
# Generated by NES Studio for the asm-only build path.
AS      = ca65
LD      = ld65
TARGET  = nes
CONFIG  = cfg/nes.cfg
ROM     = game.nes
BUILD   = build
OBJECTS = $(BUILD)/main.o $(BUILD)/graphics.o

.PHONY: all clean
all: $(ROM)

$(BUILD):
\tmkdir -p $(BUILD)

$(ROM): $(OBJECTS)
\t$(LD) -C $(CONFIG) -o $@ $(OBJECTS)

$(BUILD)/main.o: src/main.s src/scene.asminc src/palettes.asminc assets/sprites/game.chr assets/backgrounds/level.nam | $(BUILD)
\t$(AS) -t $(TARGET) -o $@ src/main.s

$(BUILD)/graphics.o: src/graphics.s assets/sprites/game.chr assets/backgrounds/level.nam | $(BUILD)
\t$(AS) -t $(TARGET) -o $@ src/graphics.s

clean:
\trm -rf $(BUILD) $(ROM)
"""
