"""Pure collision source generation for NES Studio projects."""

from __future__ import annotations

import re
from typing import Any

from .graphics import SCREEN_COLS, SCREEN_ROWS

BUILTIN_BEHAVIOUR_NAMES = {
    0: "NONE",
    1: "SOLID_GROUND",
    2: "WALL",
    3: "PLATFORM",
    4: "DOOR",
    5: "TRIGGER",
    6: "LADDER",
}

REACTION_VERB_IDS = {
    "ignore": 0,
    "block": 1,
    "land": 2,
    "land_top": 3,
    "bounce": 4,
    "exit": 5,
    "call_handler": 6,
}


def sanitise_behaviour_name(name: Any, slot_id: int) -> str:
    if slot_id in BUILTIN_BEHAVIOUR_NAMES:
        return BUILTIN_BEHAVIOUR_NAMES[slot_id]
    raw = str(name or "").upper()
    cleaned = re.sub(r"[^A-Z0-9_]+", "_", raw).strip("_")
    cleaned = re.sub(r"_+", "_", cleaned)
    if not cleaned or cleaned[0].isdigit():
        return f"CUSTOM{slot_id}"
    return cleaned


def collect_behaviour_names(state: dict[str, Any]) -> dict[int, str]:
    names: dict[int, str] = {}
    seen: set[str] = set()
    by_id: dict[int, dict[str, Any]] = {}
    for entry in state.get("behaviour_types") or []:
        if isinstance(entry, dict) and "id" in entry:
            try:
                by_id[int(entry["id"])] = entry
            except (TypeError, ValueError):
                continue
    for slot_id in range(8):
        entry = by_id.get(slot_id) or {}
        base = sanitise_behaviour_name(entry.get("name"), slot_id)
        name = base
        suffix = 2
        while name in seen:
            name = f"{base}_{suffix}"
            suffix += 1
        seen.add(name)
        names[slot_id] = name
    return names


def behaviour_world_dims(state: dict[str, Any]) -> tuple[int, int]:
    backgrounds = state.get("backgrounds")
    background: dict[str, Any] = {}
    if isinstance(backgrounds, list) and backgrounds:
        index = state.get("selectedBgIdx", 0) or 0
        if not isinstance(index, int) or not 0 <= index < len(backgrounds):
            index = 0
        candidate = backgrounds[index]
        if isinstance(candidate, dict):
            background = candidate
    dimensions = background.get("dimensions") or {}
    screens_x = max(1, int(dimensions.get("screens_x") or 1))
    screens_y = max(1, int(dimensions.get("screens_y") or 1))
    return SCREEN_COLS * screens_x, SCREEN_ROWS * screens_y


def behaviour_map_for_background(
    background: dict[str, Any] | None, columns: int, rows: int
) -> bytes:
    output = bytearray(columns * rows)
    grid = (background or {}).get("behaviour") or []
    for row_index in range(rows):
        row = grid[row_index] if row_index < len(grid) else []
        base = row_index * columns
        for column in range(columns):
            try:
                value = int(row[column]) if column < len(row) else 0
            except (TypeError, ValueError):
                value = 0
            output[base + column] = value & 0x07
    return bytes(output)


def sprite_reaction_table(state: dict[str, Any]) -> tuple[bytes, int]:
    sprites = state.get("sprites") or []
    reactions = state.get("behaviour_reactions") or []
    count = len(sprites)
    output = bytearray(count * 8)
    for sprite_index in range(count):
        reaction_map = reactions[sprite_index] if sprite_index < len(reactions) else {}
        if not isinstance(reaction_map, dict):
            reaction_map = {}
        for behaviour_id in range(8):
            verb = (
                reaction_map.get(str(behaviour_id))
                or reaction_map.get(behaviour_id)
                or "ignore"
            )
            output[sprite_index * 8 + behaviour_id] = REACTION_VERB_IDS.get(
                str(verb), 0
            )
    return bytes(output), count


def build_collision_h(state: dict[str, Any]) -> str:
    names = collect_behaviour_names(state)
    columns, rows = behaviour_world_dims(state)
    num_sprites = len(state.get("sprites") or [])
    lines = [
        "/* Auto-generated by playground_server.py — do not edit by hand. */",
        "/* Source: the Behaviour page of the tile editor.                */",
        "#ifndef COLLISION_H",
        "#define COLLISION_H",
        "",
        "/* Behaviour type ids (0..7). Slot 7 is custom — if the pupil",
        "   named it, their chosen name appears here. */",
    ]
    for slot_id in range(8):
        lines.append(f"#define BEHAVIOUR_{names[slot_id]:<16} {slot_id}")
    lines += [
        "",
        "/* Reaction verbs a sprite can have towards a behaviour id. */",
        "#define REACT_IGNORE       0",
        "#define REACT_BLOCK        1",
        "#define REACT_LAND         2",
        "#define REACT_LAND_TOP     3",
        "#define REACT_BOUNCE       4",
        "#define REACT_EXIT         5",
        "#define REACT_CALL_HANDLER 6",
        "",
        "/* World size in 8x8 tiles. Covers the full screens_x × screens_y",
        "   grid so the same data works when scrolling is added later. */",
        f"#define WORLD_COLS   {columns}",
        f"#define WORLD_ROWS   {rows}",
        f"#define NUM_BEHAVIOUR_SPRITES {num_sprites}",
        "",
        "/* Look up the behaviour id at a given world tile (8x8 grid).",
        "   Returns BEHAVIOUR_NONE (0) for out-of-range coordinates. */",
        "unsigned char behaviour_at(unsigned int world_col, unsigned int world_row);",
        "",
        "/* Look up the reaction verb a sprite has for a behaviour id.",
        "   Returns REACT_IGNORE (0) for out-of-range sprite or id. */",
        "unsigned char reaction_for(unsigned char sprite_idx, unsigned char behaviour_id);",
        "",
        "/* T2.2 — multi-bg behaviour swap.  Doors module's emitted code",
        "   calls this after a teleport so behaviour_at queries the new",
        "   room's collision data.  Out-of-range n leaves the current",
        "   map in place. */",
        "void behaviour_set_active_bg(unsigned char n);",
        "",
        "#endif",
        "",
    ]
    return "\n".join(lines)
