"""Pure full-world nametable and source generation."""

from __future__ import annotations

from typing import Any

from .graphics import SCREEN_COLS, SCREEN_ROWS


def world_nametable(
    state: dict[str, Any],
) -> tuple[bytes, bytes, int, int, int, int]:
    backgrounds = state.get("backgrounds")
    background: dict[str, Any] = {}
    if isinstance(backgrounds, list) and backgrounds:
        index = state.get("selectedBgIdx", 0) or 0
        if not isinstance(index, int) or not 0 <= index < len(backgrounds):
            index = 0
        candidate = backgrounds[index]
        if isinstance(candidate, dict):
            background = candidate
    dimensions = background.get("dimensions") or {}
    screens_x = max(1, int(dimensions.get("screens_x") or 1))
    screens_y = max(1, int(dimensions.get("screens_y") or 1))
    columns = SCREEN_COLS * screens_x
    rows = SCREEN_ROWS * screens_y

    nametable = background.get("nametable")
    if not isinstance(nametable, list):
        nametable = state.get("nametable") or []
    tiles = bytearray(columns * rows)
    for row_index in range(rows):
        row = nametable[row_index] if row_index < len(nametable) else []
        base = row_index * columns
        for column in range(columns):
            cell = row[column] if column < len(row) else None
            if isinstance(cell, dict):
                tiles[base + column] = int(cell.get("tile", 0)) & 0xFF

    attribute_columns = 8 * screens_x
    attribute_rows = 8 * screens_y
    attributes = bytearray(attribute_columns * attribute_rows)
    for screen_y in range(screens_y):
        for screen_x in range(screens_x):
            tile_row_start = screen_y * SCREEN_ROWS
            tile_column_start = screen_x * SCREEN_COLS
            for screen_row in range(8):
                for screen_column in range(8):
                    value = 0
                    for quadrant in range(4):
                        quadrant_row = (quadrant >> 1) & 1
                        quadrant_column = quadrant & 1
                        tile_row = tile_row_start + screen_row * 4 + quadrant_row * 2
                        tile_column = (
                            tile_column_start + screen_column * 4 + quadrant_column * 2
                        )
                        palette = 0
                        if tile_row < len(nametable):
                            row = nametable[tile_row]
                            if tile_column < len(row) and isinstance(row[tile_column], dict):
                                palette = int(row[tile_column].get("palette", 0)) & 3
                        value |= palette << (quadrant * 2)
                    offset = (screen_y * 8 + screen_row) * attribute_columns
                    attributes[offset + screen_x * 8 + screen_column] = value
    return (
        bytes(tiles),
        bytes(attributes),
        columns,
        rows,
        attribute_columns,
        attribute_rows,
    )


def build_bg_world_h(state: dict[str, Any]) -> str:
    _, _, columns, rows, attribute_columns, attribute_rows = world_nametable(state)
    lines = [
        "/* Auto-generated by playground_server.py — do not edit by hand. */",
        "/* Source: the Backgrounds page of the tile editor.              */",
        "#ifndef BG_WORLD_H",
        "#define BG_WORLD_H",
        "",
        "/* Full-world nametable, row-major.  Covers every screen the pupil",
        "   painted; the scroll core (Sprint 11 S-1) streams columns/rows",
        "   from this data into the off-screen nametable as the camera moves.",
        "   1x1 projects still include this header but nothing consumes it. */",
        f"#define BG_WORLD_COLS       {columns}",
        f"#define BG_WORLD_ROWS       {rows}",
        f"#define BG_WORLD_ATTR_COLS  {attribute_columns}",
        f"#define BG_WORLD_ATTR_ROWS  {attribute_rows}",
        "",
        "/* Full-world pixel dimensions.  Exposed here (rather than in",
        "   scroll.h) because main.c bounds-checks the player against them",
        "   even on the 1x1 fast path, where scroll.h is not included. */",
        "#define WORLD_W_PX          (BG_WORLD_COLS * 8)",
        "#define WORLD_H_PX          (BG_WORLD_ROWS * 8)",
        "",
        "extern const unsigned char bg_world_tiles[BG_WORLD_COLS * BG_WORLD_ROWS];",
        "extern const unsigned char bg_world_attrs[BG_WORLD_ATTR_COLS * BG_WORLD_ATTR_ROWS];",
        "",
        "#endif",
        "",
    ]
    return "\n".join(lines)


def _hex_table(name: str, size_expression: str, data: bytes) -> list[str]:
    output = [f"const unsigned char {name}[{size_expression}] = {{"]
    if not data:
        output.append("  0")
    else:
        for index in range(0, len(data), 16):
            chunk = data[index : index + 16]
            output.append("  " + ", ".join(f"0x{value:02X}" for value in chunk) + ",")
    output.append("};")
    return output


def build_bg_world_c(state: dict[str, Any]) -> str:
    tiles, attributes, columns, rows, attribute_columns, attribute_rows = world_nametable(
        state
    )
    lines = [
        "/* Auto-generated by playground_server.py — do not edit by hand. */",
        "/* Source: the Backgrounds page of the tile editor.              */",
        '#include "bg_world.h"',
        "",
        "/* Gate the arrays on world size so 1x1 builds emit no symbols,",
        "   keeping their ROM byte-identical to the pre-Sprint-11 baseline.",
        "   The scroll core only references these arrays under the same",
        "   guard — dangling externs are harmless as long as no caller",
        "   actually links against them. */",
        "#if (BG_WORLD_COLS > 32) || (BG_WORLD_ROWS > 30)",
        "",
        f"/* {columns} cols x {rows} rows of 8x8 tiles ({columns * rows} bytes). */",
    ]
    lines += _hex_table("bg_world_tiles", "BG_WORLD_COLS * BG_WORLD_ROWS", tiles)
    lines += [
        "",
        f"/* {attribute_columns} x {attribute_rows} attribute bytes ({attribute_columns * attribute_rows} bytes). */",
    ]
    lines += _hex_table(
        "bg_world_attrs", "BG_WORLD_ATTR_COLS * BG_WORLD_ATTR_ROWS", attributes
    )
    lines += ["", "#endif", ""]
    return "\n".join(lines)
