#!/usr/bin/env node

import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { gzipSync } from 'node:zlib';
import * as H from '../../../tools/builder-tests/lib/render-harness.mjs';

const OUT = path.join(H.ROOT, 'native', 'tests', 'fixtures', 'phase0', 'starters');
// Clear of run-all.mjs's allocation, which reaches 19097 for 110 suites. This
// generator is run by hand, so it must not sit in a block the runner may assign.
const PORT = 19150;

globalThis.window = globalThis;
globalThis.NES_TARGET_ENGINE = 63;
globalThis.NES_ENGINE_VERSION = 63;
for (const file of [
  'sprite-render.js',
  'builder-assembler.js',
  'builder-modules.js',
  'builder-validators.js',
  'default-state.js',
  'studio-starter.js',
]) {
  new Function(fs.readFileSync(path.join(H.WEB, file), 'utf8'))();
}

const template = H.readTemplate();
const styles = [
  ['basics', () => window.StudioStarter.create()],
  ['smb', () => window.StudioStarter.createSmb()],
  ['topdown', () => window.StudioStarter.createTopdown()],
  ['runner', () => window.StudioStarter.createRunner()],
  ['geodash', () => window.StudioStarter.createGeoDash()],
  ['racer', () => window.StudioStarter.createRacer()],
  ['scratch', () => window.StudioStarter.createScratch()],
];

function canonical(value) {
  if (Array.isArray(value)) return value.map(canonical);
  if (value && typeof value === 'object') {
    return Object.fromEntries(Object.keys(value).sort().map((key) => [key, canonical(value[key])]));
  }
  return value;
}

function jsonBytes(value) {
  return Buffer.from(JSON.stringify(canonical(value), null, 2) + '\n');
}

function sha256(bytes) {
  return createHash('sha256').update(bytes).digest('hex');
}

// The starters carry a wall-clock metadata.created/modified, so every run used
// to produce different project/play-request/source hashes for identical input.
// That cost us: it made the fixtures non-reproducible, it made three of the four
// hash columns useless as a change signal, and it silently decoupled this corpus
// from the packaged copy under src/nes_studio/resources/starters.
//
// Freezing it is inert. StarterCatalog.create() overwrites created/modified with
// the real clock on every project it makes (see tests/unit/test_starters.py), so
// no pupil ever sees this value. An obviously-synthetic epoch is used rather than
// a plausible date, so nobody reads it as when the fixture was captured.
const FROZEN_CLOCK = '1970-01-01T00:00:00.000Z';

function freezeMetadataClock(state) {
  const metadata = state?.metadata;
  if (!metadata) return;
  for (const key of ['created', 'modified']) {
    if (key in metadata) metadata[key] = FROZEN_CLOCK;
  }
}

function playerStart(state) {
  const config = state.builder?.modules?.players?.submodules?.player1?.config;
  return { x: config?.startX | 0, y: config?.startY | 0 };
}

// Capture provenance BEFORE touching the output tree — rmSync below deletes
// tracked files, which would otherwise make source_tree_dirty unconditionally
// true and the flag worthless.
const SOURCE_COMMIT = gitHead();
const SOURCE_DIRTY = gitDirty();

// Refuse before the rmSync below. Running dirty does not merely mislabel the
// manifest: this rewrites the test corpus AND the starter projects the app ships,
// from code that is not at source_commit, and the only way back is git. The
// manifest flag alone told you afterwards, once both trees had already been
// overwritten.
//
// `!== false` on purpose, so "cannot tell" refuses too. gitDirty() returns null
// when git cannot be consulted, and null is falsy -- the flag failed open, while
// its neighbour gitHead() fails closed by recording "unknown". They now agree.
if (SOURCE_DIRTY !== false && !process.argv.includes('--allow-dirty')) {
  console.error(
    SOURCE_DIRTY === null
      ? 'Refusing to run: could not ask git whether the tree is clean.'
      : 'Refusing to run: the working tree has uncommitted tracked changes.');
  console.error('  These fixtures are generated BY the code they are used to check, so');
  console.error('  source_commit must actually describe that code. Commit first, or pass');
  console.error('  --allow-dirty deliberately (the manifest then records it and');
  console.error('  test_manifest_states_its_provenance fails, which is the point).');
  process.exit(2);
}

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });

// Provenance. These fixtures are generated BY the code they are used to check,
// so the manifest has to say so rather than imply independence. See
// docs/handoffs/2026-08-06-starter-fixture-rebaseline.md.
//
// engine_version_requested is what this script asks the server for; it is a
// version STAMP. The templates and codegen that actually build the ROM are
// whatever is at the source commit below — `targetEngine` does not select an
// archived engine from tools/engines/. Those two numbers differing is expected
// and is exactly why the old "engine_version: 63" label was misleading.
function gitHead() {
  try {
    return execFileSync('git', ['rev-parse', 'HEAD'], { cwd: H.ROOT, encoding: 'utf8' }).trim();
  } catch {
    return 'unknown';
  }
}

// Tracked modifications only. An untracked scratch file in the workspace does
// not change what the generator builds, and counting it would make the flag
// permanently true — which is the same as not having the flag.
function gitDirty() {
  try {
    const out = execFileSync('git', ['status', '--porcelain', '--untracked-files=no'], {
      cwd: H.ROOT,
      encoding: 'utf8',
    });
    return out.trim() !== '';
  } catch {
    return null;
  }
}

const manifest = {
  schema_version: 2,
  what_a_pass_means:
    'These artefacts were generated by the code under test at source_commit. A ' +
    'passing test means UNCHANGED SINCE that commit. It does not mean correct.',
  source_commit: SOURCE_COMMIT,
  source_tree_dirty: SOURCE_DIRTY,
  engine_version_requested: 63,
  engine_version_at_source_commit: Number(
    fs.readFileSync(path.join(H.ROOT, 'tools', 'engines', 'ENGINE_VERSION'), 'utf8').trim(),
  ),
  generator: 'native/tests/contract/generate_phase0_starters.mjs',
  fixtures: {},
};
const { srv } = await H.startServer(PORT);
let failed = false;
try {
  for (const [id, make] of styles) {
    const state = make();
    freezeMetadataClock(state);
    const before = jsonBytes(state);
    const mainC = Buffer.from(window.BuilderAssembler.assemble(state, template));
    const request = {
      state,
      playerSpriteIdx: 0,
      playerStart: playerStart(state),
      sceneSprites: [],
      mode: 'browser',
      customMainC: mainC.toString('utf8'),
      targetEngine: 63,
    };
    const requestBytes = jsonBytes(request);
    const result = await H.buildRom(PORT, request);
    const after = jsonBytes(state);
    if (!result.ok) throw new Error(`${id}: build failed at ${result.stage}: ${result.log || ''}`);
    if (!before.equals(after)) throw new Error(`${id}: build mutated the input project`);

    const directory = path.join(OUT, id);
    fs.mkdirSync(directory, { recursive: true });
    const rom = Buffer.from(result.romBytes);
    fs.writeFileSync(path.join(directory, 'project.json.gz'), gzipSync(before, { level: 9, mtime: 0 }));
    fs.writeFileSync(path.join(directory, 'play-request.json.gz'), gzipSync(requestBytes, { level: 9, mtime: 0 }));
    fs.writeFileSync(path.join(directory, 'main.c.gz'), gzipSync(mainC, { level: 9, mtime: 0 }));
    fs.writeFileSync(path.join(directory, 'game.nes'), rom);
    manifest.fixtures[id] = {
      project_json_sha256: sha256(before),
      play_request_json_sha256: sha256(requestBytes),
      generated_source_sha256: sha256(mainC),
      rom_sha256: sha256(rom),
      rom_size: rom.length,
      input_project_unchanged: true,
    };
    console.log(`${id}: ${rom.length} bytes ${sha256(rom).slice(0, 12)}`);
  }
} catch (error) {
  failed = true;
  console.error(error?.stack || error);
} finally {
  await H.stopServer(srv);
}

if (failed) process.exit(1);
fs.writeFileSync(path.join(OUT, 'manifest.json'), jsonBytes(manifest));
console.log(`wrote ${styles.length} fixtures to ${path.relative(H.ROOT, OUT)}`);

// The app ships its own copy of the starter projects, and
// tests/unit/test_starters.py requires it to be byte-identical to this corpus.
// It used to be kept in step by hand, which is why re-baselining the corpus
// broke that test. Write both from the one source so they cannot drift again.
// Only project.json.gz ships — the ROM and generated C are test-only.
const PACKAGED = path.join(H.ROOT, 'native', 'src', 'nes_studio', 'resources', 'starters');
const packagedManifest = { schema_version: 1, generator: manifest.generator, fixtures: {} };
for (const [id] of styles) {
  const directory = path.join(PACKAGED, id);
  fs.mkdirSync(directory, { recursive: true });
  fs.copyFileSync(
    path.join(OUT, id, 'project.json.gz'),
    path.join(directory, 'project.json.gz'),
  );
  packagedManifest.fixtures[id] = { ...manifest.fixtures[id] };
}
packagedManifest.engine_version = manifest.engine_version_requested;
fs.writeFileSync(path.join(PACKAGED, 'manifest.json'), jsonBytes(packagedManifest));
console.log(`synced ${styles.length} packaged starters to ${path.relative(H.ROOT, PACKAGED)}`);
