from __future__ import annotations

import hashlib
import gzip
import json
import unittest
from pathlib import Path


FIXTURE_ROOT = Path(__file__).resolve().parents[1] / "fixtures" / "phase0" / "starters"
EXPECTED = {"basics", "smb", "topdown", "runner", "geodash", "racer", "scratch"}


def sha256(path: Path) -> str:
    data = path.read_bytes()
    if path.suffix == ".gz":
        data = gzip.decompress(data)
    return hashlib.sha256(data).hexdigest()


class PhaseZeroStarterFixtureTests(unittest.TestCase):
    def setUp(self) -> None:
        self.manifest = json.loads((FIXTURE_ROOT / "manifest.json").read_text(encoding="utf-8"))

    def test_all_shipped_starter_styles_are_materialized(self) -> None:
        self.assertEqual(set(self.manifest["fixtures"]), EXPECTED)

    def test_manifest_states_its_provenance(self) -> None:
        """A baseline generated by the code under test must say so.

        These fixtures are not an independent oracle. They were produced by the
        very generator+engine they are used to check, so a pass means "byte-for-
        byte unchanged since source_commit" and NOT "correct". If that sentence
        ever goes missing from the manifest, the gate starts reading as proof of
        correctness to whoever inherits it — so assert it is present.

        See docs/handoffs/2026-08-06-starter-fixture-rebaseline.md.
        """
        self.assertIn("what_a_pass_means", self.manifest)
        self.assertIn("does not mean correct", self.manifest["what_a_pass_means"].lower())

        commit = self.manifest["source_commit"]
        self.assertRegex(commit, r"^[0-9a-f]{40}$", "source_commit must name a real commit")
        self.assertFalse(
            self.manifest["source_tree_dirty"],
            "baselines were generated from a dirty tree, so source_commit does not "
            "describe the code that produced them — regenerate from a clean checkout",
        )

        # engine_version_requested is only a stamp; targetEngine does not select an
        # archived engine from tools/engines/. Recording both numbers is what stops
        # the old, misleading "engine_version: 63" label coming back.
        self.assertEqual(self.manifest["engine_version_requested"], 63)
        self.assertIsInstance(self.manifest["engine_version_at_source_commit"], int)

    def test_artifact_hashes_and_input_immutability_match(self) -> None:
        filenames = {
            "project_json_sha256": "project.json.gz",
            "play_request_json_sha256": "play-request.json.gz",
            "generated_source_sha256": "main.c.gz",
            "rom_sha256": "game.nes",
        }
        for fixture, record in self.manifest["fixtures"].items():
            with self.subTest(fixture=fixture):
                directory = FIXTURE_ROOT / fixture
                self.assertTrue(record["input_project_unchanged"])
                self.assertEqual(record["rom_size"], (directory / "game.nes").stat().st_size)
                for field, filename in filenames.items():
                    self.assertEqual(record[field], sha256(directory / filename))


if __name__ == "__main__":
    unittest.main()
