#!/usr/bin/env python3
"""
Playground server - one-click 'Play in NES' companion.

Serves the tile-editor web UI from tools/tile_editor_web/ and exposes a
POST /play endpoint that takes the current editor state plus a little
scene definition (which sprite is the Player, which static sprites to
drop on the background and where) and:

  1. writes the CHR + nametable into steps/Step_Playground/assets/
  2. writes palettes.inc and scene.inc into steps/Step_Playground/src/
  3. runs `make -C steps/Step_Playground` to build game.nes
  4. launches FCEUX on the freshly-built ROM

The server is intentionally a single-file stdlib-only script so it works
on any box with Python 3 and cc65 installed -- no extra dependencies.

Start from the repo root with:

    python3 tools/playground_server.py

then browse http://127.0.0.1:8765/sprites.html  (or let the VSCode task
'Start Playground Server' do it for you -- runs on folder open).
"""

from __future__ import annotations

import http.server
import json
import pathlib
import socket
import socketserver
import subprocess
import sys
import threading
import traceback
import urllib.error
import urllib.request
from urllib.parse import urlparse

ROOT = pathlib.Path(__file__).resolve().parent.parent
WEB_DIR = ROOT / "tools" / "tile_editor_web"
STEP_DIR = ROOT / "steps" / "Step_Playground"
SCENE_INC = STEP_DIR / "src" / "scene.inc"
PAL_INC = STEP_DIR / "src" / "palettes.inc"
CHR_PATH = STEP_DIR / "assets" / "sprites" / "game.chr"
NAM_PATH = STEP_DIR / "assets" / "backgrounds" / "level.nam"
PORT = 8765

SCREEN_COLS = 32
SCREEN_ROWS = 30
NUM_TILES = 256


# ---------------------------------------------------------------------------
# CHR / NAM / palette encoders
# ---------------------------------------------------------------------------

def tile_to_chr(pixels):
    """8x8 pixel grid (values 0-3) -> 16 NES CHR bytes (two bit-planes)."""
    out = bytearray(16)
    for r in range(8):
        lo = 0
        hi = 0
        row = pixels[r]
        for c in range(8):
            p = row[c] & 3
            bit = 7 - c
            lo |= (p & 1) << bit
            hi |= ((p >> 1) & 1) << bit
        out[r] = lo
        out[8 + r] = hi
    return bytes(out)


def _encode_pool(tiles, label):
    if len(tiles) != NUM_TILES:
        raise ValueError(f"expected {NUM_TILES} {label} tiles, got {len(tiles)}")
    chunk = bytearray()
    for t in tiles:
        chunk += tile_to_chr(t["pixels"])
    if len(chunk) != 4096:
        raise ValueError(f"{label} pool came out {len(chunk)} bytes, expected 4096")
    return bytes(chunk)


def build_chr(state):
    """Two independent 256-tile pools -> 8KB CHR.

    Sprite pattern table lives at $0000 (first 4KB), background pattern
    table at $1000 (second 4KB) -- matches PPU_CTRL bit 4 = 1 set by the
    step's init code. Old saves with a single `tiles` pool fall back to
    duplicating it across both tables so nothing breaks during migration.
    """
    if "sprite_tiles" in state and "bg_tiles" in state:
        return _encode_pool(state["sprite_tiles"], "sprite_tiles") \
             + _encode_pool(state["bg_tiles"], "bg_tiles")
    # Legacy single pool: shared across both tables.
    legacy = _encode_pool(state["tiles"], "tiles")
    return legacy * 2


def build_nam(state):
    """32x30 tile bytes + 64 attribute bytes = 1024-byte NES nametable."""
    nt = state.get("nametable") or []
    tiles_out = bytearray(SCREEN_COLS * SCREEN_ROWS)
    for r in range(SCREEN_ROWS):
        row = nt[r] if r < len(nt) else []
        for c in range(SCREEN_COLS):
            cell = row[c] if c < len(row) else None
            if cell:
                tiles_out[r * SCREEN_COLS + c] = int(cell.get("tile", 0)) & 0xFF

    # Attribute table: 8x8 bytes, each covers a 4x4 tile region split into
    # four 2x2 tile quads.  Quad layout in the byte: top-left=bits 0-1,
    # top-right=bits 2-3, bottom-left=bits 4-5, bottom-right=bits 6-7.
    attr_out = bytearray(64)
    for ar in range(8):
        for ac in range(8):
            byte = 0
            for quad in range(4):
                qr = (quad >> 1) & 1
                qc = quad & 1
                # top-left tile of this 2x2 quad
                tr = ar * 4 + qr * 2
                tc = ac * 4 + qc * 2
                pal = 0
                if tr < len(nt) and tc < len(nt[tr]):
                    pal = int(nt[tr][tc].get("palette", 0)) & 3
                byte |= pal << (quad * 2)
            attr_out[ar * 8 + ac] = byte

    return bytes(tiles_out) + bytes(attr_out)


def build_palettes_inc(state):
    ubg = int(state.get("universal_bg", 0x21)) & 0x3F
    lines = [
        "// generated by tools/playground_server.py - do not edit",
        "#ifndef PALETTES_INC",
        "#define PALETTES_INC",
        "",
        "static const unsigned char palette_bytes[32] = {",
    ]

    def emit(group):
        for i in range(4):
            slots = state[group][i]["slots"]
            row = [ubg, int(slots[0]) & 0x3F, int(slots[1]) & 0x3F, int(slots[2]) & 0x3F]
            lines.append("    " + ", ".join(f"0x{b:02X}" for b in row) + ",")

    emit("bg_palettes")
    emit("sprite_palettes")
    lines += ["};", "", "#endif", ""]
    return "\n".join(lines)


def cell_tile(cell):
    if cell.get("empty"):
        return 0
    return int(cell.get("tile", 0)) & 0xFF


def cell_attr(cell):
    if cell.get("empty"):
        return 0
    attr = int(cell.get("palette", 0)) & 3
    if cell.get("priority"):
        attr |= 0x20
    if cell.get("flipH"):
        attr |= 0x40
    if cell.get("flipV"):
        attr |= 0x80
    return attr & 0xFF


def build_scene_inc(state, player_idx, scene_sprites, start_x, start_y):
    sprites = state.get("sprites") or []
    if not sprites:
        raise ValueError("No sprites defined yet -- make at least one in the Sprites page.")
    if not (0 <= player_idx < len(sprites)):
        raise ValueError(f"playerSpriteIdx {player_idx} out of range (0..{len(sprites)-1})")

    lines = [
        "// generated by tools/playground_server.py - do not edit",
        "#ifndef SCENE_INC",
        "#define SCENE_INC",
        "",
    ]

    # --- Player -----------------------------------------------------------
    ps = sprites[player_idx]
    pw = int(ps["width"])
    ph = int(ps["height"])
    cells = ps["cells"]
    p_tiles = [cell_tile(cells[r][c]) for r in range(ph) for c in range(pw)]
    p_attrs = [cell_attr(cells[r][c]) for r in range(ph) for c in range(pw)]

    lines += [
        f"#define PLAYER_W {pw}",
        f"#define PLAYER_H {ph}",
        f"#define PLAYER_X {int(start_x) & 0xFF}",
        f"#define PLAYER_Y {int(start_y) & 0xFF}",
        "",
        f"static const unsigned char player_tiles[{pw*ph}] = {{",
        "    " + ", ".join(f"0x{t:02X}" for t in p_tiles),
        "};",
        f"static const unsigned char player_attrs[{pw*ph}] = {{",
        "    " + ", ".join(f"0x{a:02X}" for a in p_attrs),
        "};",
        "",
    ]

    # --- Static sprites --------------------------------------------------
    n = len(scene_sprites)
    lines.append(f"#define NUM_STATIC_SPRITES {n}")

    if n == 0:
        # cc65 rejects zero-length arrays -- keep a 1-element stub that's
        # never accessed because NUM_STATIC_SPRITES gates the loop.
        stub = (
            "static const unsigned char ss_x[1]      = { 0 };\n"
            "static const unsigned char ss_y[1]      = { 0 };\n"
            "static const unsigned char ss_w[1]      = { 0 };\n"
            "static const unsigned char ss_h[1]      = { 0 };\n"
            "static const unsigned char ss_offset[1] = { 0 };\n"
            "static const unsigned char ss_tiles[1]  = { 0 };\n"
            "static const unsigned char ss_attrs[1]  = { 0 };"
        )
        lines.append(stub)
    else:
        xs, ys, ws, hs, offsets = [], [], [], [], []
        tiles_flat, attrs_flat = [], []
        for item in scene_sprites:
            idx = int(item["spriteIdx"])
            if not (0 <= idx < len(sprites)):
                raise ValueError(f"scene sprite idx {idx} out of range")
            sp = sprites[idx]
            w = int(sp["width"])
            h = int(sp["height"])
            xs.append(int(item.get("x", 0)) & 0xFF)
            ys.append(int(item.get("y", 0)) & 0xFF)
            ws.append(w)
            hs.append(h)
            offsets.append(len(tiles_flat))
            for r in range(h):
                for c in range(w):
                    cell = sp["cells"][r][c]
                    tiles_flat.append(cell_tile(cell))
                    attrs_flat.append(cell_attr(cell))

        def arr(name, values, as_hex=False):
            fmt = (lambda v: f"0x{v:02X}") if as_hex else (lambda v: str(v))
            return (f"static const unsigned char {name}[{len(values)}] = {{ "
                    + ", ".join(fmt(v) for v in values) + " };")
        lines += [
            arr("ss_x", xs),
            arr("ss_y", ys),
            arr("ss_w", ws),
            arr("ss_h", hs),
            arr("ss_offset", offsets),
            arr("ss_tiles", tiles_flat, as_hex=True),
            arr("ss_attrs", attrs_flat, as_hex=True),
        ]

    lines += ["", "#endif", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Build + launch pipeline
# ---------------------------------------------------------------------------

def run_play(body):
    state = body.get("state")
    if not isinstance(state, dict):
        return {"ok": False, "stage": "input", "log": "missing 'state' in request body"}

    player_idx = int(body.get("playerSpriteIdx", 0))
    scene_sprites = body.get("sceneSprites") or []
    start = body.get("playerStart") or {}
    start_x = int(start.get("x", 60))
    start_y = int(start.get("y", 120))

    try:
        chr_bytes = build_chr(state)
        nam_bytes = build_nam(state)
        pal_src = build_palettes_inc(state)
        scene_src = build_scene_inc(state, player_idx, scene_sprites, start_x, start_y)
    except Exception as e:
        return {"ok": False, "stage": "generate", "log": f"{type(e).__name__}: {e}\n\n{traceback.format_exc()}"}

    CHR_PATH.parent.mkdir(parents=True, exist_ok=True)
    NAM_PATH.parent.mkdir(parents=True, exist_ok=True)
    SCENE_INC.parent.mkdir(parents=True, exist_ok=True)

    CHR_PATH.write_bytes(chr_bytes)
    NAM_PATH.write_bytes(nam_bytes)
    SCENE_INC.write_text(scene_src)
    PAL_INC.write_text(pal_src)

    build = subprocess.run(
        ["make", "-C", str(STEP_DIR)],
        capture_output=True, text=True,
    )
    build_log = (build.stdout or "") + (build.stderr or "")
    if build.returncode != 0:
        return {"ok": False, "stage": "build", "log": build_log}

    rom = STEP_DIR / "game.nes"
    if not rom.exists():
        return {"ok": False, "stage": "build", "log": build_log + "\ngame.nes missing after build"}

    # Launch FCEUX detached -- we do NOT wait on it, so the pupil can keep
    # playing while the server accepts further 'Play' presses.
    try:
        subprocess.Popen(
            ["fceux", str(rom)],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            start_new_session=True,
        )
    except FileNotFoundError:
        return {"ok": False, "stage": "launch",
                "log": build_log + "\nfceux is not on PATH"}
    except Exception as e:
        return {"ok": False, "stage": "launch",
                "log": build_log + f"\nfailed to launch fceux: {e}"}

    return {"ok": True, "stage": "launched", "log": build_log, "rom": str(rom)}


# ---------------------------------------------------------------------------
# HTTP plumbing
# ---------------------------------------------------------------------------

class Handler(http.server.SimpleHTTPRequestHandler):
    # Serve static files out of WEB_DIR.
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(WEB_DIR), **kwargs)

    def end_headers(self):
        self.send_header("Cache-Control", "no-store")
        self.send_header("Access-Control-Allow-Origin", "*")
        super().end_headers()

    def do_GET(self):
        parsed = urlparse(self.path)
        if parsed.path == "/health":
            return self._json(200, {"ok": True})
        return super().do_GET()

    def do_OPTIONS(self):
        self.send_response(204)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "POST, GET, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()

    def do_POST(self):
        parsed = urlparse(self.path)
        if parsed.path != "/play":
            return self.send_error(404)
        length = int(self.headers.get("Content-Length", "0") or "0")
        raw = self.rfile.read(length)
        try:
            body = json.loads(raw.decode("utf-8"))
        except Exception as e:
            return self._json(400, {"ok": False, "stage": "input", "log": f"bad JSON: {e}"})
        try:
            result = run_play(body)
        except Exception:
            result = {"ok": False, "stage": "server", "log": traceback.format_exc()}
        self._json(200 if result.get("ok") else 500, result)

    def _json(self, code, obj):
        data = json.dumps(obj).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def log_message(self, fmt, *args):  # keep the server log tidy
        sys.stderr.write("[playground] " + (fmt % args) + "\n")


class ThreadedHTTPServer(socketserver.ThreadingMixIn, http.server.HTTPServer):
    daemon_threads = True
    allow_reuse_address = True


def _port_in_use(host, port):
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.settimeout(0.3)
        try:
            s.connect((host, port))
            return True
        except OSError:
            return False


def _ping_existing_playground(host, port):
    """Return True if something on host:port already speaks our /health."""
    try:
        req = urllib.request.Request(f"http://{host}:{port}/health")
        with urllib.request.urlopen(req, timeout=0.5) as r:
            body = json.loads(r.read().decode("utf-8"))
            return bool(body.get("ok"))
    except (urllib.error.URLError, OSError, ValueError):
        return False


def main():
    if not WEB_DIR.exists():
        sys.exit(f"web dir not found: {WEB_DIR}")
    if not STEP_DIR.exists():
        sys.exit(f"step dir not found: {STEP_DIR}")

    # Idempotent start: VSCode's 'runOn: folderOpen' can fire this task more
    # than once across window reloads.  If another playground server is
    # already listening, just print a friendly message and exit 0.
    if _port_in_use("127.0.0.1", PORT):
        if _ping_existing_playground("127.0.0.1", PORT):
            print(
                f"Playground server already running on http://127.0.0.1:{PORT}/ -- nothing to do.\n"
                f"  Editor:  http://127.0.0.1:{PORT}/index.html\n"
                f"  Sprites: http://127.0.0.1:{PORT}/sprites.html",
                file=sys.stderr, flush=True,
            )
            return
        sys.exit(
            f"Port {PORT} is in use by something else (not a playground server).\n"
            f"  Find it with:  lsof -iTCP:{PORT} -sTCP:LISTEN\n"
            f"  Or change PORT at the top of tools/playground_server.py."
        )

    srv = ThreadedHTTPServer(("127.0.0.1", PORT), Handler)
    banner = (
        f"Playground server listening on http://127.0.0.1:{PORT}/\n"
        f"  Editor:    http://127.0.0.1:{PORT}/index.html\n"
        f"  Sprites:   http://127.0.0.1:{PORT}/sprites.html\n"
        f"Press Ctrl-C to stop."
    )
    print(banner, file=sys.stderr, flush=True)
    try:
        srv.serve_forever()
    except KeyboardInterrupt:
        srv.shutdown()
        print("stopped", file=sys.stderr)


if __name__ == "__main__":
    main()
