"""Load the icons.

Generated by `scripts/generate_icons.py` from NES pixel art — every colour is an
index into the real NES system palette, because an icon for an NES tool should
not contain a colour an NES cannot produce.

Before these existed the app had no icon at all: not in the launcher, not in the
task switcher, not on the window. On a locked-down school image, an application
with no icon looks like one that does not belong there.
"""

from __future__ import annotations

from functools import lru_cache
from importlib import resources

from PySide6.QtCore import Qt
from PySide6.QtGui import QIcon, QPixmap

#: The sizes the app icon is generated at, largest last.
APP_ICON_SIZES: tuple[int, ...] = (16, 32, 48, 64, 128, 256)


def _load(name: str) -> QPixmap | None:
    try:
        data = resources.files("nes_studio.resources.icons").joinpath(name).read_bytes()
    except (FileNotFoundError, ModuleNotFoundError):
        return None
    pixmap = QPixmap()
    return pixmap if pixmap.loadFromData(data, "PNG") else None


@lru_cache(maxsize=1)
def app_icon() -> QIcon:
    """The application icon, at every size the desktop might ask for."""

    icon = QIcon()
    for size in APP_ICON_SIZES:
        pixmap = _load(f"nes-studio-{size}.png")
        if pixmap is not None:
            icon.addPixmap(pixmap)
    return icon


@lru_cache(maxsize=16)
def mode_icon(mode_id: str) -> QIcon:
    """The rail icon for a mode. An empty `QIcon` if it has none — the rail still
    shows the mode's name, so a missing icon degrades to what we had before."""

    pixmap = _load(f"mode-{mode_id.lower()}.png")
    return QIcon(pixmap) if pixmap is not None else QIcon()


@lru_cache(maxsize=8)
def locked_mode_icon(mode_id: str) -> QIcon:
    """The same icon, dimmed — a locked mode stays *visible*."""

    pixmap = _load(f"mode-{mode_id.lower()}.png")
    if pixmap is None:
        return QIcon()
    faded = QPixmap(pixmap.size())
    faded.fill(Qt.GlobalColor.transparent)

    from PySide6.QtGui import QPainter

    painter = QPainter(faded)
    painter.setOpacity(0.35)
    painter.drawPixmap(0, 0, pixmap)
    painter.end()
    return QIcon(faded)
