/* Auto-generated by playground_server.py — do not edit by hand. */
/* Source: the Behaviour page of the tile editor.                */
#include "collision.h"

/* World behaviour map: 32 cols x 30 rows, row-major. All zeros in
   the committed stub — the playground server overwrites this file
   with the pupil's actual behaviour painting before every build. */
const unsigned char behaviour_map[32 * 30] = { 0 };

/* Sprite x behaviour reaction table.
   No sprites defined yet — stub table so the build still links. */
const unsigned char sprite_reactions[8] = { 0, 0, 0, 0, 0, 0, 0, 0 };

unsigned char behaviour_at(unsigned int world_col, unsigned int world_row) {
  if (world_col >= WORLD_COLS) return BEHAVIOUR_NONE;
  if (world_row >= WORLD_ROWS) return BEHAVIOUR_NONE;
  return behaviour_map[world_row * WORLD_COLS + world_col];
}

unsigned char reaction_for(unsigned char sprite_idx, unsigned char behaviour_id) {
  if (behaviour_id >= 8) return REACT_IGNORE;
  if (sprite_idx >= 1) return REACT_IGNORE;
  return sprite_reactions[((unsigned int)sprite_idx << 3) | behaviour_id];
}
