/* Auto-generated by playground_server.py — do not edit by hand. */
/* Source: the Backgrounds page of the tile editor.              */
#ifndef BG_WORLD_H
#define BG_WORLD_H

/* Full-world nametable, row-major.  Covers every screen the pupil
   painted; the scroll core (Sprint 11 S-1) streams columns/rows
   from this data into the off-screen nametable as the camera moves.
   1x1 projects still include this header but nothing consumes it. */
#define BG_WORLD_COLS       32
#define BG_WORLD_ROWS       30
#define BG_WORLD_ATTR_COLS  8
#define BG_WORLD_ATTR_ROWS  8

/* Full-world pixel dimensions.  Exposed here (rather than in scroll.h)
   because main.c bounds-checks the player against them even on the
   1x1 fast path, where scroll.h is not included. */
#define WORLD_W_PX          (BG_WORLD_COLS * 8)
#define WORLD_H_PX          (BG_WORLD_ROWS * 8)

extern const unsigned char bg_world_tiles[BG_WORLD_COLS * BG_WORLD_ROWS];
extern const unsigned char bg_world_attrs[BG_WORLD_ATTR_COLS * BG_WORLD_ATTR_ROWS];

#endif
