/* Auto-generated by playground_server.py — do not edit by hand. */
/* Source: the Backgrounds page of the tile editor.              */
#include "bg_world.h"

/* Stub body: the committed copy is an empty 32x30 world so a fresh
   make succeeds before the server has ever written real data.  The
   server overwrites this file on every build. */
const unsigned char bg_world_tiles[BG_WORLD_COLS * BG_WORLD_ROWS] = { 0 };
const unsigned char bg_world_attrs[BG_WORLD_ATTR_COLS * BG_WORLD_ATTR_ROWS] = { 0 };
