/* Auto-generated by playground_server.py — do not edit by hand. */
/* Source: the Behaviour page of the tile editor.                */
#ifndef COLLISION_H
#define COLLISION_H

/* Behaviour type ids (0..7). Slot 7 is custom — if the pupil
   named it, their chosen name appears here. */
#define BEHAVIOUR_NONE             0
#define BEHAVIOUR_SOLID_GROUND     1
#define BEHAVIOUR_WALL             2
#define BEHAVIOUR_PLATFORM         3
#define BEHAVIOUR_DOOR             4
#define BEHAVIOUR_TRIGGER          5
#define BEHAVIOUR_LADDER           6
#define BEHAVIOUR_CUSTOM7          7

/* Reaction verbs a sprite can have towards a behaviour id. */
#define REACT_IGNORE       0
#define REACT_BLOCK        1
#define REACT_LAND         2
#define REACT_LAND_TOP     3
#define REACT_BOUNCE       4
#define REACT_EXIT         5
#define REACT_CALL_HANDLER 6

/* World size in 8x8 tiles. Covers the full screens_x × screens_y
   grid so the same data works when scrolling is added later. */
#define WORLD_COLS   32
#define WORLD_ROWS   30
#define NUM_BEHAVIOUR_SPRITES 1

/* Look up the behaviour id at a given world tile (8x8 grid).
   Returns BEHAVIOUR_NONE (0) for out-of-range coordinates. */
unsigned char behaviour_at(unsigned int world_col, unsigned int world_row);

/* Look up the reaction verb a sprite has for a behaviour id.
   Returns REACT_IGNORE (0) for out-of-range sprite or id. */
unsigned char reaction_for(unsigned char sprite_idx, unsigned char behaviour_id);

#endif
