;
; File generated by cc65 v 2.18 - Debian 2.19-2
;
	.fopt		compiler,"cc65 v 2.18 - Debian 2.19-2"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_waitvsync
	.import		_load_background
	.export		_main

.segment	"DATA"

_game_state:
	.byte	$00
_active_npc:
	.byte	$00
_enemy1_x:
	.byte	$96
_enemy1_y:
	.byte	$C0
_enemy1_dir:
	.byte	$01
_enemy1_left:
	.byte	$78
_enemy1_right:
	.byte	$C8
_enemy2_x:
	.byte	$50
_enemy2_y:
	.byte	$80
_enemy2_dir:
	.byte	$01
_enemy2_left:
	.byte	$40
_enemy2_right:
	.byte	$70
_enemy_timer:
	.byte	$00
_enemy_speed:
	.byte	$03
_npc1_x:
	.byte	$28
_npc1_y:
	.byte	$C0
_npc2_x:
	.byte	$D2
_npc2_y:
	.byte	$C0
_gem_x:
	.byte	$64
	.byte	$8C
	.byte	$B4
	.byte	$58
_gem_y:
	.byte	$A8
	.byte	$A8
	.byte	$A8
	.byte	$68
_gem_collected:
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
_heart_x:
	.byte	$B0
_heart_y:
	.byte	$68
_heart_collected:
	.byte	$00
_score:
	.byte	$00

.segment	"RODATA"

_anim_tiles:
	.byte	$01
	.byte	$02
	.byte	$11
	.byte	$12
	.byte	$21
	.byte	$22
	.byte	$31
	.byte	$32
	.byte	$09
	.byte	$0A
	.byte	$19
	.byte	$1A
	.byte	$29
	.byte	$2A
	.byte	$39
	.byte	$3A
	.byte	$01
	.byte	$02
	.byte	$11
	.byte	$12
	.byte	$21
	.byte	$22
	.byte	$31
	.byte	$32
	.byte	$0B
	.byte	$0C
	.byte	$1B
	.byte	$1C
	.byte	$2B
	.byte	$2C
	.byte	$3B
	.byte	$3C
_msg1_line1:
	.byte	$11
	.byte	$21
	.byte	$10
	.byte	$25
	.byte	$14
	.byte	$34
	.byte	$17
	.byte	$14
	.byte	$21
	.byte	$1E
	.byte	$35
	.byte	$00
_msg1_line2:
	.byte	$11
	.byte	$14
	.byte	$26
	.byte	$10
	.byte	$21
	.byte	$14
	.byte	$34
	.byte	$23
	.byte	$17
	.byte	$14
	.byte	$34
	.byte	$22
	.byte	$1B
	.byte	$18
	.byte	$1C
	.byte	$14
	.byte	$00
_msg1_line3:
	.byte	$18
	.byte	$1D
	.byte	$34
	.byte	$23
	.byte	$17
	.byte	$14
	.byte	$34
	.byte	$25
	.byte	$10
	.byte	$1B
	.byte	$1B
	.byte	$14
	.byte	$28
	.byte	$37
	.byte	$00
_msg2_line1:
	.byte	$26
	.byte	$14
	.byte	$1B
	.byte	$12
	.byte	$1E
	.byte	$1C
	.byte	$14
	.byte	$35
	.byte	$00
_msg2_line2:
	.byte	$16
	.byte	$14
	.byte	$1C
	.byte	$22
	.byte	$34
	.byte	$15
	.byte	$1E
	.byte	$21
	.byte	$34
	.byte	$22
	.byte	$10
	.byte	$1B
	.byte	$14
	.byte	$00
_msg2_line3:
	.byte	$2F
	.byte	$2A
	.byte	$34
	.byte	$14
	.byte	$10
	.byte	$12
	.byte	$17
	.byte	$37
	.byte	$00

.segment	"BSS"

_x:
	.res	1,$00
_y:
	.res	1,$00
_pad:
	.res	1,$00
_prev_pad:
	.res	1,$00
_jump:
	.res	1,$00
_jmptime:
	.res	1,$00
_plrdir:
	.res	1,$00
_moved:
	.res	1,$00
_moveWait:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ ppu_seek (unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_ppu_seek: near

.segment	"CODE"

	jsr     pusha
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	sta     $2006
	ldy     #$00
	ldx     #$00
	lda     (sp),y
	sta     $2006
	jsr     incsp2
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ reset_scroll (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_reset_scroll: near

.segment	"CODE"

	ldx     #$00
	lda     #$00
	sta     $2005
	ldx     #$00
	lda     #$00
	sta     $2005
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ set_cell (unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_set_cell: near

.segment	"CODE"

	jsr     pusha
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	ldx     #$00
	jsr     shlax4
	jsr     shlax1
	jsr     pushax
	ldx     #$20
	lda     #$00
	jsr     tosaddax
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	ldx     #$00
	sta     $2006
	ldy     #$01
	jsr     ldaxysp
	ldx     #$00
	ldx     #$00
	sta     $2006
	jsr     incsp4
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ write_palettes (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_write_palettes: near

.segment	"CODE"

	lda     #$3F
	jsr     pusha
	lda     #$00
	jsr     _ppu_seek
	ldx     #$00
	lda     #$21
	sta     $2007
	ldx     #$00
	lda     #$29
	sta     $2007
	ldx     #$00
	lda     #$19
	sta     $2007
	ldx     #$00
	lda     #$0F
	sta     $2007
	lda     #$3F
	jsr     pusha
	lda     #$05
	jsr     _ppu_seek
	ldx     #$00
	lda     #$00
	sta     $2007
	ldx     #$00
	lda     #$10
	sta     $2007
	ldx     #$00
	lda     #$2D
	sta     $2007
	lda     #$3F
	jsr     pusha
	lda     #$11
	jsr     _ppu_seek
	ldx     #$00
	lda     #$30
	sta     $2007
	ldx     #$00
	lda     #$27
	sta     $2007
	ldx     #$00
	lda     #$17
	sta     $2007
	lda     #$3F
	jsr     pusha
	lda     #$15
	jsr     _ppu_seek
	ldx     #$00
	lda     #$1A
	sta     $2007
	ldx     #$00
	lda     #$30
	sta     $2007
	ldx     #$00
	lda     #$0A
	sta     $2007
	lda     #$3F
	jsr     pusha
	lda     #$19
	jsr     _ppu_seek
	ldx     #$00
	lda     #$30
	sta     $2007
	ldx     #$00
	lda     #$16
	sta     $2007
	ldx     #$00
	lda     #$07
	sta     $2007
	lda     #$3F
	jsr     pusha
	lda     #$1D
	jsr     _ppu_seek
	ldx     #$00
	lda     #$16
	sta     $2007
	ldx     #$00
	lda     #$27
	sta     $2007
	ldx     #$00
	lda     #$06
	sta     $2007
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ init_player (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_player: near

.segment	"CODE"

	ldx     #$00
	lda     #$3C
	sta     _x
	ldx     #$00
	lda     #$B0
	sta     _y
	ldx     #$00
	lda     #$00
	sta     _pad
	ldx     #$00
	lda     #$00
	sta     _prev_pad
	ldx     #$00
	lda     #$01
	sta     _jump
	ldx     #$00
	lda     #$00
	sta     _jmptime
	ldx     #$00
	lda     #$00
	sta     _plrdir
	ldx     #$00
	lda     #$00
	sta     _moved
	ldx     #$00
	lda     #$00
	sta     _moveWait
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ init_game (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_game: near

.segment	"CODE"

	jsr     _waitvsync
	ldx     #$00
	lda     #$00
	sta     $2001
	jsr     _write_palettes
	jsr     _load_background
	ldx     #$00
	lda     #$10
	sta     $2000
	jsr     _reset_scroll
	ldx     #$00
	lda     #$1E
	sta     $2001
	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ read_controller (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_read_controller: near

.segment	"CODE"

	lda     #$00
	jsr     pusha
	jsr     decsp1
	ldx     #$00
	lda     #$01
	sta     $4016
	ldx     #$00
	lda     #$00
	sta     $4016
	ldx     #$00
	lda     #$00
	ldy     #$00
	sta     (sp),y
L0123:	ldy     #$00
	ldx     #$00
	lda     (sp),y
	cmp     #$08
	jsr     boolult
	jne     L0126
	jmp     L0124
L0126:	ldy     #$01
	ldx     #$00
	lda     (sp),y
	jsr     shlax1
	ldy     #$01
	sta     (sp),y
	ldx     #$00
	lda     $4016
	ldx     #$00
	and     #$01
	stx     tmp1
	ora     tmp1
	jeq     L0125
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	ora     #$01
	ldy     #$01
	sta     (sp),y
L0125:	ldy     #$00
	ldx     #$00
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	jmp     L0123
L0124:	ldy     #$01
	ldx     #$00
	lda     (sp),y
	jmp     L011B
L011B:	jsr     incsp2
	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ overlap (unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_overlap: near

.segment	"CODE"

	jsr     pusha
	ldy     #$07
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	ldy     #$07
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	ldy     #$05
	ldx     #$00
	lda     (sp),y
	jsr     tosuleax
	jeq     L0134
	ldx     #$00
	lda     #$00
	jmp     L0133
L0134:	ldy     #$03
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	ldy     #$09
	ldx     #$00
	lda     (sp),y
	jsr     tosuleax
	jeq     L0137
	ldx     #$00
	lda     #$00
	jmp     L0133
L0137:	ldy     #$06
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	ldy     #$06
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	jsr     tosuleax
	jeq     L013A
	ldx     #$00
	lda     #$00
	jmp     L0133
L013A:	ldy     #$02
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	ldy     #$08
	ldx     #$00
	lda     (sp),y
	jsr     tosuleax
	jeq     L013D
	ldx     #$00
	lda     #$00
	jmp     L0133
L013D:	ldx     #$00
	lda     #$01
	jmp     L0133
L0133:	jsr     incsp8
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ write_padded (__near__ const unsigned char *, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_write_padded: near

.segment	"CODE"

	jsr     pusha
	lda     #$00
	jsr     pusha
	lda     #$00
	jsr     pusha
	jmp     L0146
L0144:	ldy     #$04
	jsr     ldaxysp
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	ldy     #$00
	jsr     ldauidx
	sta     $2007
	ldy     #$01
	ldx     #$00
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	ldy     #$00
	ldx     #$00
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
L0146:	ldy     #$04
	jsr     ldaxysp
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	ldy     #$00
	jsr     ldauidx
	cmp     #$00
	jsr     boolne
	jeq     L0149
	ldy     #$00
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	jsr     tosultax
	jne     L0147
L0149:	ldx     #$00
	lda     #$00
	jeq     L014A
L0147:	ldx     #$00
	lda     #$01
L014A:	jne     L0144
	jmp     L0153
L0151:	ldx     #$00
	lda     #$34
	sta     $2007
	ldy     #$00
	ldx     #$00
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
L0153:	ldy     #$00
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	jsr     tosultax
	jne     L0151
	jsr     incsp5
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ draw_box_frame (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_box_frame: near

.segment	"CODE"

	jsr     decsp2
	lda     #$02
	jsr     pusha
	lda     #$05
	jsr     _set_cell
	ldx     #$00
	lda     #$3B
	sta     $2007
	ldx     #$00
	lda     #$01
	ldy     #$00
	sta     (sp),y
L0160:	ldy     #$00
	ldx     #$00
	lda     (sp),y
	cmp     #$15
	jsr     boolult
	jne     L0163
	jmp     L0161
L0163:	ldx     #$00
	lda     #$3F
	sta     $2007
	ldy     #$00
	ldx     #$00
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	jmp     L0160
L0161:	ldx     #$00
	lda     #$3C
	sta     $2007
	ldx     #$00
	lda     #$01
	ldy     #$01
	sta     (sp),y
L016E:	ldy     #$01
	ldx     #$00
	lda     (sp),y
	cmp     #$04
	jsr     boolult
	jne     L0171
	jmp     L016F
L0171:	ldy     #$01
	ldx     #$00
	lda     (sp),y
	jsr     incax2
	ldx     #$00
	jsr     pusha
	lda     #$05
	jsr     _set_cell
	ldx     #$00
	lda     #$41
	sta     $2007
	ldx     #$00
	lda     #$01
	ldy     #$00
	sta     (sp),y
L017C:	ldy     #$00
	ldx     #$00
	lda     (sp),y
	cmp     #$15
	jsr     boolult
	jne     L017F
	jmp     L017D
L017F:	ldx     #$00
	lda     #$34
	sta     $2007
	ldy     #$00
	ldx     #$00
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	jmp     L017C
L017D:	ldx     #$00
	lda     #$42
	sta     $2007
	ldy     #$01
	ldx     #$00
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	jmp     L016E
L016F:	lda     #$06
	jsr     pusha
	lda     #$05
	jsr     _set_cell
	ldx     #$00
	lda     #$3D
	sta     $2007
	ldx     #$00
	lda     #$01
	ldy     #$00
	sta     (sp),y
L0190:	ldy     #$00
	ldx     #$00
	lda     (sp),y
	cmp     #$15
	jsr     boolult
	jne     L0193
	jmp     L0191
L0193:	ldx     #$00
	lda     #$40
	sta     $2007
	ldy     #$00
	ldx     #$00
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	jmp     L0190
L0191:	ldx     #$00
	lda     #$3E
	sta     $2007
	jsr     incsp2
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ erase_box (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_erase_box: near

.segment	"CODE"

	jsr     decsp2
	ldx     #$00
	lda     #$00
	ldy     #$01
	sta     (sp),y
L019F:	ldy     #$01
	ldx     #$00
	lda     (sp),y
	cmp     #$05
	jsr     boolult
	jne     L01A2
	jmp     L01A0
L01A2:	ldy     #$01
	ldx     #$00
	lda     (sp),y
	jsr     incax2
	ldx     #$00
	jsr     pusha
	lda     #$05
	jsr     _set_cell
	ldx     #$00
	lda     #$00
	ldy     #$00
	sta     (sp),y
L01AA:	ldy     #$00
	ldx     #$00
	lda     (sp),y
	cmp     #$16
	jsr     boolult
	jne     L01AD
	jmp     L01A1
L01AD:	ldx     #$00
	lda     #$00
	sta     $2007
	ldy     #$00
	ldx     #$00
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	jmp     L01AA
L01A1:	ldy     #$01
	ldx     #$00
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	jmp     L019F
L01A0:	jsr     incsp2
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ show_dialogue (__near__ const unsigned char *, __near__ const unsigned char *, __near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_show_dialogue: near

.segment	"CODE"

	jsr     pushax
	jsr     _waitvsync
	ldx     #$00
	lda     #$00
	sta     $2001
	jsr     _draw_box_frame
	lda     #$03
	jsr     pusha
	lda     #$07
	jsr     _set_cell
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	lda     #$12
	jsr     _write_padded
	lda     #$04
	jsr     pusha
	lda     #$07
	jsr     _set_cell
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	lda     #$12
	jsr     _write_padded
	lda     #$05
	jsr     pusha
	lda     #$07
	jsr     _set_cell
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	lda     #$12
	jsr     _write_padded
	jsr     _reset_scroll
	ldx     #$00
	lda     #$1E
	sta     $2001
	jsr     incsp6
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ hide_dialogue (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_hide_dialogue: near

.segment	"CODE"

	jsr     _waitvsync
	ldx     #$00
	lda     #$00
	sta     $2001
	jsr     _erase_box
	jsr     _reset_scroll
	ldx     #$00
	lda     #$1E
	sta     $2001
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ step_walk (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_step_walk: near

.segment	"CODE"

	ldx     #$00
	inc     _moveWait
	lda     _moveWait
	ldx     #$00
	lda     _moveWait
	cmp     #$07
	lda     #$00
	ldx     #$00
	rol     a
	jeq     L01E3
	ldx     #$00
	inc     _moved
	lda     _moved
	ldx     #$00
	lda     #$00
	sta     _moveWait
L01E3:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ update_player (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_update_player: near

.segment	"CODE"

	ldx     #$00
	lda     _pad
	ldx     #$00
	and     #$08
	stx     tmp1
	ora     tmp1
	jeq     L01EC
	lda     _jump
	jeq     L01EC
	ldx     #$00
	lda     _jmptime
	cmp     #$00
	jsr     booleq
	jne     L01EA
L01EC:	ldx     #$00
	lda     #$00
	jeq     L01ED
L01EA:	ldx     #$00
	lda     #$01
L01ED:	jeq     L01E9
	ldx     #$00
	lda     _y
	sec
	sbc     #$03
	sta     _y
	ldx     #$00
	lda     #$0F
	sta     _jmptime
L01E9:	ldx     #$00
	lda     _pad
	ldx     #$00
	and     #$04
	stx     tmp1
	ora     tmp1
	jeq     L01F5
	ldx     #$00
	lda     _y
	cmp     #$B0
	jsr     boolult
	jne     L01F3
L01F5:	ldx     #$00
	lda     #$00
	jeq     L01F6
L01F3:	ldx     #$00
	lda     #$01
L01F6:	jeq     L01F2
	ldx     #$00
	inc     _y
	lda     _y
L01F2:	ldx     #$00
	lda     _pad
	ldx     #$00
	and     #$02
	stx     tmp1
	ora     tmp1
	jeq     L01F8
	ldx     #$00
	dec     _x
	lda     _x
	ldx     #$00
	lda     #$40
	sta     _plrdir
	jsr     _step_walk
L01F8:	ldx     #$00
	lda     _pad
	ldx     #$00
	and     #$01
	stx     tmp1
	ora     tmp1
	jeq     L01FE
	ldx     #$00
	inc     _x
	lda     _x
	ldx     #$00
	lda     #$00
	sta     _plrdir
	jsr     _step_walk
L01FE:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ apply_gravity (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_apply_gravity: near

.segment	"CODE"

	ldx     #$00
	lda     _y
	cmp     #$B0
	jsr     boolult
	jeq     L0205
	ldx     #$00
	lda     #$00
	sta     _jump
	lda     _jmptime
	jeq     L0209
	ldx     #$00
	dec     _jmptime
	lda     _jmptime
	ldx     #$00
	lda     _y
	sec
	sbc     #$03
	sta     _y
	jmp     L020E
L0209:	ldx     #$00
	lda     #$03
	clc
	adc     _y
	sta     _y
L020E:	jmp     L0211
L0205:	ldx     #$00
	lda     #$01
	sta     _jump
L0211:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ patrol_enemy (__near__ unsigned char *, __near__ unsigned char *, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_patrol_enemy: near

.segment	"CODE"

	jsr     pusha
	ldy     #$03
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jeq     L0215
	ldy     #$05
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	ldx     #$00
	lda     #$01
	clc
	adc     (ptr1),y
	sta     (ptr1),y
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	jsr     tosugeax
	jeq     L0218
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staspidx
L0218:	jmp     L021E
L0215:	ldy     #$05
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	ldx     #$00
	lda     (ptr1),y
	sec
	sbc     #$01
	sta     (ptr1),y
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	jsr     tosuleax
	jeq     L021E
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$01
	ldy     #$00
	jsr     staspidx
L021E:	jsr     incsp6
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ update_enemies (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_update_enemies: near

.segment	"CODE"

	ldx     #$00
	inc     _enemy_timer
	lda     _enemy_timer
	ldx     #$00
	lda     _enemy_timer
	jsr     pushax
	ldx     #$00
	lda     _enemy_speed
	jsr     tosultax
	jeq     L0224
	jmp     L0222
L0224:	ldx     #$00
	lda     #$00
	sta     _enemy_timer
	lda     #<(_enemy1_x)
	ldx     #>(_enemy1_x)
	jsr     pushax
	lda     #<(_enemy1_dir)
	ldx     #>(_enemy1_dir)
	jsr     pushax
	lda     _enemy1_left
	jsr     pusha
	lda     _enemy1_right
	jsr     _patrol_enemy
	lda     #<(_enemy2_x)
	ldx     #>(_enemy2_x)
	jsr     pushax
	lda     #<(_enemy2_dir)
	ldx     #>(_enemy2_dir)
	jsr     pushax
	lda     _enemy2_left
	jsr     pusha
	lda     _enemy2_right
	jsr     _patrol_enemy
L0222:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ collect_items (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_collect_items: near

.segment	"CODE"

	jsr     decsp1
	ldx     #$00
	lda     #$00
	ldy     #$00
	sta     (sp),y
L0233:	ldy     #$00
	ldx     #$00
	lda     (sp),y
	cmp     #$04
	jsr     boolult
	jne     L0236
	jmp     L0234
L0236:	lda     #<(_gem_collected)
	ldx     #>(_gem_collected)
	ldy     #$00
	clc
	adc     (sp),y
	bcc     L023E
	inx
L023E:	ldy     #$00
	jsr     ldauidx
	jsr     bnega
	jeq     L023F
	lda     _x
	jsr     pusha
	lda     _y
	jsr     pusha
	lda     #$10
	jsr     pusha
	lda     #$20
	jsr     pusha
	lda     #<(_gem_x)
	ldx     #>(_gem_x)
	ldy     #$04
	clc
	adc     (sp),y
	bcc     L0246
	inx
L0246:	ldy     #$00
	jsr     ldauidx
	jsr     pusha
	lda     #<(_gem_y)
	ldx     #>(_gem_y)
	ldy     #$05
	clc
	adc     (sp),y
	bcc     L0249
	inx
L0249:	ldy     #$00
	jsr     ldauidx
	jsr     pusha
	lda     #$08
	jsr     pusha
	lda     #$08
	jsr     _overlap
	tax
	jne     L023C
L023F:	ldx     #$00
	lda     #$00
	jeq     L024C
L023C:	ldx     #$00
	lda     #$01
L024C:	jeq     L0235
	lda     #<(_gem_collected)
	ldx     #>(_gem_collected)
	ldy     #$00
	clc
	adc     (sp),y
	bcc     L024F
	inx
L024F:	jsr     pushax
	ldx     #$00
	lda     #$01
	ldy     #$00
	jsr     staspidx
	ldx     #$00
	inc     _score
	lda     _score
L0235:	ldy     #$00
	ldx     #$00
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	jmp     L0233
L0234:	ldx     #$00
	lda     _heart_collected
	jsr     bnega
	jeq     L0254
	lda     _x
	jsr     pusha
	lda     _y
	jsr     pusha
	lda     #$10
	jsr     pusha
	lda     #$20
	jsr     pusha
	lda     _heart_x
	jsr     pusha
	lda     _heart_y
	jsr     pusha
	lda     #$08
	jsr     pusha
	lda     #$08
	jsr     _overlap
	tax
	jne     L0253
L0254:	ldx     #$00
	lda     #$00
	jeq     L025D
L0253:	ldx     #$00
	lda     #$01
L025D:	jeq     L0252
	ldx     #$00
	lda     #$01
	sta     _heart_collected
L0252:	jsr     incsp1
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ talk_to_npc (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_talk_to_npc: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	ldx     #$00
	lda     (sp),y
	sta     _active_npc
	ldy     #$00
	ldx     #$00
	lda     (sp),y
	cmp     #$01
	jsr     booleq
	jeq     L0263
	lda     #<(_msg1_line1)
	ldx     #>(_msg1_line1)
	jsr     pushax
	lda     #<(_msg1_line2)
	ldx     #>(_msg1_line2)
	jsr     pushax
	lda     #<(_msg1_line3)
	ldx     #>(_msg1_line3)
	jsr     _show_dialogue
	jmp     L0269
L0263:	lda     #<(_msg2_line1)
	ldx     #>(_msg2_line1)
	jsr     pushax
	lda     #<(_msg2_line2)
	ldx     #>(_msg2_line2)
	jsr     pushax
	lda     #<(_msg2_line3)
	ldx     #>(_msg2_line3)
	jsr     _show_dialogue
L0269:	ldx     #$00
	lda     #$01
	sta     _game_state
	ldx     #$00
	lda     _pad
	sta     _prev_pad
	jsr     incsp1
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ update_playing (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_update_playing: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	lda     (sp),y
	jeq     L0275
	lda     _x
	jsr     pusha
	lda     _y
	jsr     pusha
	lda     #$10
	jsr     pusha
	lda     #$20
	jsr     pusha
	ldx     #$00
	lda     _npc1_x
	jsr     decax4
	ldx     #$00
	jsr     pusha
	lda     _npc1_y
	jsr     pusha
	lda     #$18
	jsr     pusha
	lda     #$10
	jsr     _overlap
	tax
	jne     L0274
L0275:	ldx     #$00
	lda     #$00
	jeq     L027E
L0274:	ldx     #$00
	lda     #$01
L027E:	jeq     L0273
	lda     #$01
	jsr     _talk_to_npc
	jmp     L0272
L0273:	ldy     #$00
	lda     (sp),y
	jeq     L0283
	lda     _x
	jsr     pusha
	lda     _y
	jsr     pusha
	lda     #$10
	jsr     pusha
	lda     #$20
	jsr     pusha
	ldx     #$00
	lda     _npc2_x
	jsr     decax4
	ldx     #$00
	jsr     pusha
	lda     _npc2_y
	jsr     pusha
	lda     #$18
	jsr     pusha
	lda     #$10
	jsr     _overlap
	tax
	jne     L0282
L0283:	ldx     #$00
	lda     #$00
	jeq     L028C
L0282:	ldx     #$00
	lda     #$01
L028C:	jeq     L0281
	lda     #$02
	jsr     _talk_to_npc
	jmp     L0272
L0281:	jsr     _update_player
	jsr     _apply_gravity
	jsr     _update_enemies
	jsr     _collect_items
L0272:	jsr     incsp1
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ update_dialogue (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_update_dialogue: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	lda     (sp),y
	jeq     L0294
	jsr     _hide_dialogue
	ldx     #$00
	lda     #$00
	sta     _game_state
	ldx     #$00
	lda     #$00
	sta     _active_npc
L0294:	jsr     incsp1
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ draw_sprite (unsigned char, unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_sprite: near

.segment	"CODE"

	jsr     pusha
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	sta     $2004
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	sta     $2004
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	sta     $2004
	ldy     #$00
	ldx     #$00
	lda     (sp),y
	sta     $2004
	jsr     incsp4
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ draw_player (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_player: near

.segment	"CODE"

	jsr     decsp3
	ldx     #$00
	lda     _moved
	ldx     #$00
	and     #$03
	jsr     aslax3
	clc
	adc     #<(_anim_tiles)
	tay
	txa
	adc     #>(_anim_tiles)
	tax
	tya
	jsr     pushax
	ldx     #$00
	lda     _plrdir
	cmp     #$40
	jsr     booleq
	jeq     L02AB
	ldx     #$00
	lda     _x
	jsr     incax8
	ldx     #$00
	ldy     #$03
	sta     (sp),y
	ldx     #$00
	lda     _x
	ldy     #$02
	sta     (sp),y
	jmp     L02B1
L02AB:	ldx     #$00
	lda     _x
	ldy     #$03
	sta     (sp),y
	ldx     #$00
	lda     _x
	jsr     incax8
	ldx     #$00
	ldy     #$02
	sta     (sp),y
L02B1:	ldx     #$00
	lda     #$00
	ldy     #$04
	sta     (sp),y
L02B6:	ldy     #$04
	ldx     #$00
	lda     (sp),y
	cmp     #$04
	jsr     boolult
	jne     L02B9
	jmp     L02B7
L02B9:	ldx     #$00
	lda     _y
	jsr     pushax
	ldy     #$06
	ldx     #$00
	lda     (sp),y
	jsr     aslax3
	jsr     tosaddax
	ldx     #$00
	jsr     pusha
	ldy     #$02
	jsr     ldaxysp
	jsr     pushax
	ldy     #$07
	ldx     #$00
	lda     (sp),y
	jsr     aslax1
	jsr     tosaddax
	ldy     #$00
	jsr     ldauidx
	jsr     pusha
	lda     _plrdir
	jsr     pusha
	ldy     #$06
	lda     (sp),y
	jsr     _draw_sprite
	ldx     #$00
	lda     _y
	jsr     pushax
	ldy     #$06
	ldx     #$00
	lda     (sp),y
	jsr     aslax3
	jsr     tosaddax
	ldx     #$00
	jsr     pusha
	ldy     #$02
	jsr     ldaxysp
	jsr     pushax
	ldy     #$07
	ldx     #$00
	lda     (sp),y
	jsr     aslax1
	jsr     incax1
	jsr     tosaddax
	ldy     #$00
	jsr     ldauidx
	jsr     pusha
	lda     _plrdir
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     _draw_sprite
	ldy     #$04
	ldx     #$00
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	jmp     L02B6
L02B7:	jsr     incsp5
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ draw_enemy (unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_enemy: near

.segment	"CODE"

	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$09
	lda     (sp),y
	jsr     _draw_sprite
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$09
	ldx     #$00
	lda     (sp),y
	jsr     incax8
	ldx     #$00
	jsr     _draw_sprite
	ldy     #$05
	ldx     #$00
	lda     (sp),y
	jsr     incax8
	ldx     #$00
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$09
	lda     (sp),y
	jsr     _draw_sprite
	ldy     #$05
	ldx     #$00
	lda     (sp),y
	jsr     incax8
	ldx     #$00
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$09
	ldx     #$00
	lda     (sp),y
	jsr     incax8
	ldx     #$00
	jsr     _draw_sprite
	jsr     incsp7
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ draw_npcs (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_npcs: near

.segment	"CODE"

	lda     _npc1_y
	jsr     pusha
	lda     #$60
	jsr     pusha
	lda     #$02
	jsr     pusha
	lda     _npc1_x
	jsr     _draw_sprite
	lda     _npc1_y
	jsr     pusha
	lda     #$61
	jsr     pusha
	lda     #$02
	jsr     pusha
	ldx     #$00
	lda     _npc1_x
	jsr     incax8
	ldx     #$00
	jsr     _draw_sprite
	ldx     #$00
	lda     _npc1_y
	jsr     incax8
	ldx     #$00
	jsr     pusha
	lda     #$70
	jsr     pusha
	lda     #$02
	jsr     pusha
	lda     _npc1_x
	jsr     _draw_sprite
	ldx     #$00
	lda     _npc1_y
	jsr     incax8
	ldx     #$00
	jsr     pusha
	lda     #$71
	jsr     pusha
	lda     #$02
	jsr     pusha
	ldx     #$00
	lda     _npc1_x
	jsr     incax8
	ldx     #$00
	jsr     _draw_sprite
	lda     _npc2_y
	jsr     pusha
	lda     #$62
	jsr     pusha
	lda     #$03
	jsr     pusha
	lda     _npc2_x
	jsr     _draw_sprite
	lda     _npc2_y
	jsr     pusha
	lda     #$63
	jsr     pusha
	lda     #$03
	jsr     pusha
	ldx     #$00
	lda     _npc2_x
	jsr     incax8
	ldx     #$00
	jsr     _draw_sprite
	ldx     #$00
	lda     _npc2_y
	jsr     incax8
	ldx     #$00
	jsr     pusha
	lda     #$72
	jsr     pusha
	lda     #$03
	jsr     pusha
	lda     _npc2_x
	jsr     _draw_sprite
	ldx     #$00
	lda     _npc2_y
	jsr     incax8
	ldx     #$00
	jsr     pusha
	lda     #$73
	jsr     pusha
	lda     #$03
	jsr     pusha
	ldx     #$00
	lda     _npc2_x
	jsr     incax8
	ldx     #$00
	jsr     _draw_sprite
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ draw_items (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_items: near

.segment	"CODE"

	jsr     decsp1
	ldx     #$00
	lda     #$00
	ldy     #$00
	sta     (sp),y
L030C:	ldy     #$00
	ldx     #$00
	lda     (sp),y
	cmp     #$04
	jsr     boolult
	jne     L030F
	jmp     L030D
L030F:	lda     #<(_gem_collected)
	ldx     #>(_gem_collected)
	ldy     #$00
	clc
	adc     (sp),y
	bcc     L0317
	inx
L0317:	ldy     #$00
	jsr     ldauidx
	jeq     L0318
	ldx     #$00
	lda     #$FF
	jmp     L031A
L0318:	lda     #<(_gem_y)
	ldx     #>(_gem_y)
	ldy     #$00
	clc
	adc     (sp),y
	bcc     L031D
	inx
L031D:	ldy     #$00
	jsr     ldauidx
	ldx     #$00
L031A:	ldx     #$00
	jsr     pusha
	lda     #$48
	jsr     pusha
	lda     #$03
	jsr     pusha
	lda     #<(_gem_collected)
	ldx     #>(_gem_collected)
	ldy     #$03
	clc
	adc     (sp),y
	bcc     L0322
	inx
L0322:	ldy     #$00
	jsr     ldauidx
	jeq     L0323
	ldx     #$00
	lda     #$00
	jmp     L0325
L0323:	lda     #<(_gem_x)
	ldx     #>(_gem_x)
	ldy     #$03
	clc
	adc     (sp),y
	bcc     L0328
	inx
L0328:	ldy     #$00
	jsr     ldauidx
	ldx     #$00
L0325:	ldx     #$00
	jsr     _draw_sprite
	ldy     #$00
	ldx     #$00
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	jmp     L030C
L030D:	lda     _heart_collected
	jeq     L032B
	ldx     #$00
	lda     #$FF
	jmp     L032D
L032B:	ldx     #$00
	lda     _heart_y
	ldx     #$00
L032D:	ldx     #$00
	jsr     pusha
	lda     #$49
	jsr     pusha
	lda     #$03
	jsr     pusha
	lda     _heart_collected
	jeq     L0332
	ldx     #$00
	lda     #$00
	jmp     L0334
L0332:	ldx     #$00
	lda     _heart_x
	ldx     #$00
L0334:	ldx     #$00
	jsr     _draw_sprite
	jsr     incsp1
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ game_update (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_game_update: near

.segment	"CODE"

	jsr     decsp1
	jsr     _read_controller
	sta     _pad
	ldx     #$00
	lda     _pad
	ldx     #$00
	and     #$80
	stx     tmp1
	ora     tmp1
	jeq     L033C
	ldx     #$00
	lda     _prev_pad
	ldx     #$00
	and     #$80
	jsr     bnegax
	jne     L033A
L033C:	ldx     #$00
	lda     #$00
	jeq     L033E
L033A:	ldx     #$00
	lda     #$01
L033E:	ldx     #$00
	ldy     #$00
	sta     (sp),y
	ldx     #$00
	lda     _game_state
	cmp     #$00
	jsr     booleq
	jeq     L033F
	ldy     #$00
	lda     (sp),y
	jsr     _update_playing
	jmp     L0343
L033F:	ldy     #$00
	lda     (sp),y
	jsr     _update_dialogue
L0343:	ldx     #$00
	lda     _pad
	sta     _prev_pad
	jsr     incsp1
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ game_draw (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_game_draw: near

.segment	"CODE"

	jsr     _waitvsync
	jsr     _reset_scroll
	ldx     #$00
	lda     #$00
	sta     $2003
	jsr     _draw_player
	jsr     _draw_npcs
	lda     _enemy1_x
	jsr     pusha
	lda     _enemy1_y
	jsr     pusha
	lda     #$40
	jsr     pusha
	lda     #$41
	jsr     pusha
	lda     #$50
	jsr     pusha
	lda     #$51
	jsr     pusha
	lda     #$01
	jsr     _draw_enemy
	lda     _enemy2_x
	jsr     pusha
	lda     _enemy2_y
	jsr     pusha
	lda     #$44
	jsr     pusha
	lda     #$45
	jsr     pusha
	lda     #$54
	jsr     pusha
	lda     #$55
	jsr     pusha
	lda     #$02
	jsr     _draw_enemy
	jsr     _draw_items
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     _init_player
	jsr     _init_game
	jmp     L0366
L0364:	jsr     _game_update
	jsr     _game_draw
L0366:	jmp     L0364
	rts

.endproc

